### ISSUE TITLE
Snapshot restore with unicode characters

### ISSUE THREAD

**Issue by ciscovoice** [SoCo/SoCo#281]
I've been writing a full security system for my house and used some of your example code to get a lot of my TTS for notifications and what not working. This stuff is excellent and I appreciate all the hard work you guys put into it. It's fantastic. 

I have one question however, and it was eluded to else on the SoCo boards, is about unicode encoding on the return function of snapshot (this is affected on both the plugin version or the new built-in to SoCo snapshot function).

``` python
$ ./TestSnap2.py 
Zone Player: Living Room  - Coordinator Living Room
{'NextURI': u'', 'CurrentURI': 'pndrradio:1673412035410938911', 'NextURIMetaData': u'', 'RecordMedium': 'NOT_IMPLEMENTED', 'PlayMedium': 'NETWORK', 'NrTracks': '4', 'WriteStatus': 'NOT_IMPLEMENTED', 'MediaDuration': 'NOT_IMPLEMENTED', 'CurrentURIMetaData': u'<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="OOOX1673412035410938911" parentID="0" restricted="true"><dc:title>Michael Bubl\xe9 Radio</dc:title><upnp:class>object.item.audioItem.audioBroadcast.sonos-favorite</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON3_xxxx@xxxx.com</desc></item></DIDL-Lite>'}
pndrradio:1673412035410938911
stream
{u'mute': False, u'volume': 1, u'source': u'stream', u'state': 'PAUSED_PLAYBACK', u'media_uri': 'pndrradio:1673412035410938911', u'media_meta': u'<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="OOOX1673412035410938911" parentID="0" restricted="true"><dc:title>Michael Bubl\xe9 Radio</dc:title><upnp:class>object.item.audioItem.audioBroadcast.sonos-favorite</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON3_xxxx@xxxx.com</desc></item></DIDL-Lite>'}
   > Image print for zone: Living Room
           mute: False
         volume: 1
         source: stream
          state: PAUSED_PLAYBACK
      media_uri: pndrradio:1673412035410938911
     media_meta: <DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="OOOX1673412035410938911" parentID="0" restricted="true"><dc:title>**Michael BublÃ© Radio**</dc:title><upnp:class>object.item.audioItem.audioBroadcast.sonos-favorite</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON3_xxxx@xxxx.com</desc></item></DIDL-Lite>

resetting zones
Resetting Zone Player: Living Room
Traceback (most recent call last):
  File "./TestSnap2.py", line 65, in <module>
    zp.my_snap.restore(fade=True)
  File "/usr/local/lib/python2.7/dist-packages/soco/plugins/snapshot.py", line 152, in restore
    ('CurrentURIMetaData', restore_meta)
  File "/usr/local/lib/python2.7/dist-packages/soco/services.py", line 159, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/soco/services.py", line 333, in send_command
    self.base_url + self.control_url, headers=headers, data=body)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 518, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 330, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 962, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 996, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 958, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 822, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 794, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 719: ordinal not in range(128)
```
If the radio station has a special character, accents, etc, it wont 'return' back to. I tried to encode everything at various points in the code to get around it, but I'm apparently not doing it correctly. Did you guys ever figure out how to get around that? 

Thanks much!

**Comment by DPH** [comment]
Hi @ciscovoice,
I assume you are having problems with the snapshot, not the TTS
The snapshot functionality is now in the formal SoCo (release0.10 onwards) https://pypi.python.org/pypi/soco/

This does cater for accented radio stations from memory and is part of normal code not a plugin.
See SoCo pull request #224 SoCo/SoCo#224

Hope this helps,
Cheers David

**Comment by ciscovoice** [comment]
Python 2.7 with soco 0.10 didn't seem to like it. I converted my code to python3 and it seems to have fixed itself. Thanks for the great info. Keep up the good work.

**Comment by KennethNielsen** [comment]
@ciscovoice if it fails with python 2.7, then it is a bug. The only question is whether there were improvements on this code between 0.10 and now (@DPH  do you know).

Just on the top of my head, the snapshot.py file does not import unicode_literals from __future__, that might have something to do with it if any strings are created anywhere in the module.

**Comment by DPH** [comment]
Hi @KennethNielsen,
agree it is a bug - I am sure it did work with radio station names with accents.

Have tested 0.10 and the current version under Python 2.7 on Windows and can confirm both fail!
Have done a file compare on snapshot.py 0.10 and current and no real differences.

Had a look but I am not sure how to fix it. 
Tried adding from __future__ import unicode_literals but did not help
Have always struggled with Unicode in Python!
Welcome others input

Cheers David

**Comment by lawrenceakka** [comment]
It seems to be working for me. Can someone tell me steps to reproduce?

L

**Comment by ciscovoice** [comment]
I can give you my code, but I don't think I saved a 2.7 version. The python 3.2 on raspberry pi version seems to play nice thought if you want it.

**Comment by DPH** [comment]
Hi @lawrenceakka 
 on python 2.7 the following errors with the latest soco

```
# -*- coding: utf-8 -*-
import time
import soco
from soco.snapshot import Snapshot

start_uri = u'x-sonosapi-stream:s148801?sid=254&flags=32&sn=0'
alert = 'http://archive.org/download/TenD2005-07-16.flac16/TenD2005-07-16t10Wonderboy_64kb.mp3'

#choose device and start playing a radio station
device = soco.SoCo('192.168.1.72')
device.play_uri(start_uri, '', 'test accented radio station')
time.sleep(5)

#take snapshot of current state
snap = Snapshot(device)
is_coord = snap.snapshot()

# Do something here that changes what's playing etc.
device.volume = 10
if is_coord:
    device.play_uri(alert, '', 'my alert')
time.sleep(4)

#restore with fade = True
snap.restore(True)
```

cheers David

**Comment by lawrenceakka** [comment]
That's very helpful. Thanks.  I found the bug and fixed it.

**Comment by DPH** [comment]
Great investigation @lawrenceakka 
Works perfectly now
Thank you

Cheers David
