### ISSUE TITLE
sonos discover broken in Python3

### ISSUE THREAD

**Issue by Utsav2** [SoCo/SoCo#304]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.2/dist-packages/soco/core.py", line 100, in discover
    if "Sonos" not in data:
TypeError: Type str doesn't support the buffer API

'3.2.3 (default, Feb 27 2014, 21:31:18) [GCC 4.6.3]'

**Comment by Utsav2** [comment]
prints this out in the python2 version

set([SoCo("10.0.0.8")])

**Comment by Utsav2** [comment]
Never mind, noticed #298
