### ISSUE TITLE
SoCo v0.11 installation problems on Raspberry Pi

### ISSUE THREAD

**Issue by ekstroem** [SoCo/SoCo#312]
Hi all,

Was trying to get get SoCo v0.11 up and running on my Raspberry Pi using the following commands from a scratch installation:

```
sudo apt-get install python3
sudo apt-get install python3-pip

sudo pip-3.2 install requests
sudo pip-3.2 install soco
```

The last line results in

```
Downloading/unpacking soco
  Downloading soco-0.11.tar.gz (95Kb): 95Kb downloaded
  Running setup.py egg_info for package soco
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/pi/build/soco/setup.py", line 63, in <module>
        LONG_DESCRIPTION = file.read()
      File "/usr/lib/python3.2/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3743: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/build/soco/setup.py", line 63, in <module>

    LONG_DESCRIPTION = file.read()

  File "/usr/lib/python3.2/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3743: ordinal not in range(128)

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/pi/build/soco
Storing complete log in /root/.pip/pip.log
```

Can anyone point me in the right direction on how to fix this?

**Comment by stefankoegl** [comment]
I've prepared a fix in #313.

Can you please test it with

````
pip install git+https://github.com/SoCo/SoCo.git@setup-encoding#egg=soco-dev
```` 

and let me know if everything works as expected?

**Comment by ekstroem** [comment]
Yup. That is working.

I ran (just in case someone wants to copy and paste the exact commands to install everything)
```
sudo pip-3.2 install git+https://github.com/SoCo/SoCo.git@setup-encoding#egg=soco-dev
```
and everything is spiffing! Music is flowing everywhere!

Thanks a bunch and keep up the good work!

**Comment by stefankoegl** [comment]
I have release version 0.11.1, so a simple

    pip install soco

should now be enough.
