### ISSUE TITLE
unittests/test_integration.py failing:  'DidlMusicTrack' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by dundeemt** [SoCo/SoCo#342]
While working on tests for Issue #341 I was getting ready to create tests against a live device and encountered failures in the test_integration.py module.   This test must not have been run by anyone in some time.  It is trying to access the 'uri' element of a DidlMusicTrack, which does not exist.  'uri' is an element of the DidlMusicTrack.resources[0].  Also, it is being accessed as a dictionary item which doesn't fit with current examples.

  `soco.add_to_queue(track['uri'])`

```python
(soco)jlh@d520:~/projects/soco/SoCo$ py.test -vvxs --ip 192.168.2.151 unittest/test_integration.py 
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.6 -- py-1.4.30 -- pytest-2.7.2 -- /home/jlh/projects/soco/bin/python
rootdir: /home/jlh/projects/soco/SoCo, inifile: setup.cfg
plugins: cov
collected 22 items 

unittest/test_integration.py::TestVolume::test_get_and_set PASSED
unittest/test_integration.py::TestVolume::test_invalid_arguments PASSED
unittest/test_integration.py::TestVolume::test_set_0 PASSED
unittest/test_integration.py::TestBass::test_get_and_set PASSED
unittest/test_integration.py::TestBass::test_invalid_arguments PASSED
unittest/test_integration.py::TestTreble::test_get_and_set PASSED
unittest/test_integration.py::TestTreble::test_invalid_arguments PASSED
unittest/test_integration.py::TestMute::test PASSED
unittest/test_integration.py::TestGetCurrentTransportInfo::test PASSED
unittest/test_integration.py::TestTransport::test_pause_and_play PASSED
unittest/test_integration.py::TestTransport::test_stop PASSED
unittest/test_integration.py::TestTransport::test_seek_valid PASSED
unittest/test_integration.py::TestTransport::test_seek_invald PASSED
unittest/test_integration.py::TestGetCurrentTrackInfo::test_get FAILED
Traceback (most recent call last):
  File "/home/jlh/projects/soco/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/config.py", line 41, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
    return self._docall(self.methods, kwargs)
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
    firstresult=self.firstresult).execute()
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
    res = method(*args)
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/main.py", line 116, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/main.py", line 109, in wrap_session
    exitstatus=session.exitstatus)
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
    return self._docall(self.methods, kwargs)
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
    firstresult=self.firstresult).execute()
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/core.py", line 393, in execute
    return wrapped_call(method(*args), self.execute)
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/core.py", line 109, in wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/terminal.py", line 356, in pytest_sessionfinish
    outcome.get_result()
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/core.py", line 138, in get_result
    py.builtin._reraise(*ex)
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/core.py", line 123, in __init__
    self.result = func()
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
    res = method(*args)
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/runner.py", line 55, in pytest_sessionfinish
    session._setupstate.teardown_all()
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/runner.py", line 375, in teardown_all
    self._pop_and_teardown()
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/runner.py", line 348, in _pop_and_teardown
    self._teardown_with_finalization(colitem)
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/runner.py", line 366, in _teardown_with_finalization
    self._callfinalizers(colitem)
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/runner.py", line 363, in _callfinalizers
    py.builtin._reraise(*exc)
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/runner.py", line 356, in _callfinalizers
    fin()
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/python.py", line 1868, in finish
    func()
  File "/home/jlh/projects/soco/local/lib/python2.7/site-packages/_pytest/python.py", line 1826, in teardown
    next()
  File "/home/jlh/projects/soco/SoCo/unittest/test_integration.py", line 67, in soco
    soco.add_to_queue(track['uri'])
TypeError: 'DidlMusicTrack' object has no attribute '__getitem__'
```

Is there an open issue for this test module already and I'm just not finding it?  If not, I'll start on a pr to fix the existing issues in the suite before I try and add new tests.

**Comment by dundeemt** [comment]
closed wit pr #343
