### ISSUE TITLE
Event Error if there is no title text

### ISSUE THREAD

**Issue by robwebset** [SoCo/SoCo#374]
I was messing about with the latest code base and hit an error:

```
NOTICE: Exception happened during processing of request from
NOTICE: ('192.168.0.16', 55129)
ERROR: Traceback (most recent call last):
ERROR:   File "C:\Kodi\Kodi-15-Isengard\system\python\Lib\SocketServer.py", line 595, in process_request_thread
ERROR:     self.finish_request(request, client_address)
ERROR:   File "C:\Kodi\Kodi-15-Isengard\system\python\Lib\SocketServer.py", line 334, in finish_request
ERROR:     self.RequestHandlerClass(request, client_address, self)
ERROR:   File "C:\Kodi\Kodi-15-Isengard\system\python\Lib\SocketServer.py", line 651, in __init__
ERROR:     self.handle()
ERROR:   File "C:\Kodi\Kodi-15-Isengard\system\python\Lib\BaseHTTPServer.py", line 340, in handle
ERROR:     self.handle_one_request()
ERROR:   File "C:\Kodi\Kodi-15-Isengard\system\python\Lib\BaseHTTPServer.py", line 328, in handle_one_request
ERROR:     method()
ERROR:   File "C:\Kodi\Kodi-15-Isengard\portable_data\addons\script.sonos\resources\lib\soco\events.py", line 227, in do_NOTIFY
ERROR:     variables = parse_event_xml(content)
ERROR:   File "C:\Kodi\Kodi-15-Isengard\portable_data\addons\script.sonos\resources\lib\soco\events.py", line 130, in parse_event_xml
ERROR:     value = from_didl_string(value)[0]
ERROR:   File "C:\Kodi\Kodi-15-Isengard\portable_data\addons\script.sonos\resources\lib\soco\data_structures.py", line 93, in from_didl_string
ERROR:     items.append(cls.from_element(elt))
ERROR:   File "C:\Kodi\Kodi-15-Isengard\portable_data\addons\script.sonos\resources\lib\soco\data_structures.py", line 501, in from_element
ERROR:     title = really_unicode(title_elt.text)
ERROR:   File "C:\Kodi\Kodi-15-Isengard\portable_data\addons\script.sonos\resources\lib\soco\utils.py", line 43, in really_unicode
ERROR:     raise ValueError('%s is not a string at all.' % in_string)
ERROR: ValueError: None is not a string at all.
```

The message I believe it was trying to process was:

```
Event content: <e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0"><e:property><LastChange>&lt;Event xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/AVT/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;&lt;InstanceID val=&quot;0&quot;&gt;&lt;TransportState val=&quot;PAUSED_PLAYBACK&quot;/&gt;&lt;CurrentPlayMode val=&quot;SHUFFLE_NOREPEAT&quot;/&gt;&lt;CurrentCrossfadeMode val=&quot;0&quot;/&gt;&lt;NumberOfTracks val=&quot;8539&quot;/&gt;&lt;CurrentTrack val=&quot;2&quot;/&gt;&lt;CurrentSection val=&quot;0&quot;/&gt;&lt;CurrentTrackURI val=&quot;x-file-cifs://192.168.0.3/Music/Various%20Artists/Various%20Comedy%20Songs/03%20-%20A%20Tribe%20Of%20Toffs%20-%20John%20Ketley%20Is%20A%20Weatherman.mp3&quot;/&gt;&lt;CurrentTrackDuration val=&quot;0:03:20&quot;/&gt;&lt;CurrentTrackMetaData val=&quot;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;-1&amp;quot; parentID=&amp;quot;-1&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;res protocolInfo=&amp;quot;x-file-cifs:*:audio/mpeg:*&amp;quot; duration=&amp;quot;0:03:20&amp;quot;&amp;gt;x-file-cifs://192.168.0.3/Music/Various%20Artists/Various%20Comedy%20Songs/03%20-%20A%20Tribe%20Of%20Toffs%20-%20John%20Ketley%20Is%20A%20Weatherman.mp3&amp;lt;/res&amp;gt;&amp;lt;r:streamContent&amp;gt;&amp;lt;/r:streamContent&amp;gt;&amp;lt;r:radioShowMd&amp;gt;&amp;lt;/r:radioShowMd&amp;gt;&amp;lt;upnp:albumArtURI&amp;gt;/getaa?u=x-file-cifs%3a%2f%2f192.168.0.3%2fMusic%2fVarious%2520Artists%2fVarious%2520Comedy%2520Songs%2f03%2520-%2520A%2520Tribe%2520Of%2520Toffs%2520-%2520John%2520Ketley%2520Is%2520A%2520Weatherman.mp3&amp;amp;amp;v=3&amp;lt;/upnp:albumArtURI&amp;gt;&amp;lt;dc:title&amp;gt;John Ketley Is A Weatherman&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioItem.musicTrack&amp;lt;/upnp:class&amp;gt;&amp;lt;dc:creator&amp;gt;A Tribe Of Toffs&amp;lt;/dc:creator&amp;gt;&amp;lt;upnp:album&amp;gt;Various Comedy Songs&amp;lt;/upnp:album&amp;gt;&amp;lt;upnp:originalTrackNumber&amp;gt;3&amp;lt;/upnp:originalTrackNumber&amp;gt;&amp;lt;r:albumArtist&amp;gt;A Tribe Of Toffs&amp;lt;/r:albumArtist&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&quot;/&gt;&lt;r:NextTrackURI val=&quot;x-file-cifs://192.168.0.3/Music/FLAC/Placebo/Meds/10%20-%20Broken%20Promise%20(feat.%20Michael%20Stipe).flac&quot;/&gt;&lt;r:NextTrackMetaData val=&quot;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;-1&amp;quot; parentID=&amp;quot;-1&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;res protocolInfo=&amp;quot;x-file-cifs:*:audio/flac:*&amp;quot; duration=&amp;quot;0:04:12&amp;quot;&amp;gt;x-file-cifs://192.168.0.3/Music/FLAC/Placebo/Meds/10%20-%20Broken%20Promise%20(feat.%20Michael%20Stipe).flac&amp;lt;/res&amp;gt;&amp;lt;upnp:albumArtURI&amp;gt;/getaa?u=x-file-cifs%3a%2f%2f192.168.0.3%2fMusic%2fFLAC%2fPlacebo%2fMeds%2f10%2520-%2520Broken%2520Promise%2520(feat.%2520Michael%2520Stipe).flac&amp;amp;amp;v=3&amp;lt;/upnp:albumArtURI&amp;gt;&amp;lt;dc:title&amp;gt;Broken Promise (feat. Michael Stipe)&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioItem.musicTrack&amp;lt;/upnp:class&amp;gt;&amp;lt;dc:creator&amp;gt;Placebo&amp;lt;/dc:creator&amp;gt;&amp;lt;upnp:album&amp;gt;Meds&amp;lt;/upnp:album&amp;gt;&amp;lt;upnp:originalTrackNumber&amp;gt;10&amp;lt;/upnp:originalTrackNumber&amp;gt;&amp;lt;r:albumArtist&amp;gt;Placebo&amp;lt;/r:albumArtist&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&quot;/&gt;&lt;r:EnqueuedTransportURI val=&quot;x-file-cifs://192.168.0.3/Music/Various%20Artists/Various%20Comedy%20Songs/03%20-%20A%20Tribe%20Of%20Toffs%20-%20John%20Ketley%20Is%20A%20Weatherman.mp3&quot;/&gt;&lt;r:EnqueuedTransportURIMetaData val=&quot;&amp;lt;DIDL-Lite xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot; xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;&amp;quot; parentID=&amp;quot;&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title /&amp;gt;&amp;lt;res protocolInfo=&amp;quot;x-rincon-playlist:*:*:*&amp;quot;&amp;gt;x-file-cifs://192.168.0.3/Music/Various%20Artists/Various%20Comedy%20Songs/03%20-%20A%20Tribe%20Of%20Toffs%20-%20John%20Ketley%20Is%20A%20Weatherman.mp3&amp;lt;/res&amp;gt;&amp;lt;upnp:class&amp;gt;object&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;RINCON_AssociatedZPUDN&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&quot;/&gt;&lt;PlaybackStorageMedium val=&quot;NETWORK&quot;/&gt;&lt;AVTransportURI val=&quot;x-rincon-queue:RINCON_000E58C8FC4601400#0&quot;/&gt;&lt;AVTransportURIMetaData val=&quot;&quot;/&gt;&lt;NextAVTransportURI val=&quot;&quot;/&gt;&lt;NextAVTransportURIMetaData val=&quot;&quot;/&gt;&lt;CurrentTransportActions val=&quot;Set, Play, Stop, Pause, Seek, Next, Previous&quot;/&gt;&lt;r:CurrentValidPlayModes val=&quot;SHUFFLE,REPEAT,CROSSFADE&quot;/&gt;&lt;r:MuseSessions val=&quot;&quot;/&gt;&lt;TransportStatus val=&quot;OK&quot;/&gt;&lt;r:SleepTimerGeneration val=&quot;0&quot;/&gt;&lt;r:AlarmRunning val=&quot;0&quot;/&gt;&lt;r:SnoozeRunning val=&quot;0&quot;/&gt;&lt;r:RestartPending val=&quot;0&quot;/&gt;&lt;TransportPlaySpeed val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;CurrentMediaDuration val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;RecordStorageMedium val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;PossiblePlaybackStorageMedia val=&quot;NONE, NETWORK&quot;/&gt;&lt;PossibleRecordStorageMedia val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;RecordMediumWriteStatus val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;CurrentRecordQualityMode val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;PossibleRecordQualityModes val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;/InstanceID&gt;&lt;/Event&gt;</LastChange></e:property></e:propertyset>
```

I'm a bit rusty on all this (having not looked at it for a long time), but I think maybe a change to data_structure.py:

```
        # There must be a title. According to spec, it should be the first
        # child, but Sonos does not abide by this
        title_elt = element.find(ns_tag('dc', 'title'))
        if title_elt is None:
            raise DIDLMetadataError(
                "Missing title element")
        title = really_unicode(title_elt.text)
```

To allow for the case where title_elt.text is None?

**Comment by robwebset** [comment]
Sorry, just found another one:

```
NOTICE: Exception happened during processing of request from
NOTICE: ('192.168.0.16', 55162)
ERROR: Traceback (most recent call last):
ERROR:   File "C:\Kodi\Kodi-15-Isengard\system\python\Lib\SocketServer.py", line 595, in process_request_thread
ERROR:     self.finish_request(request, client_address)
ERROR:   File "C:\Kodi\Kodi-15-Isengard\system\python\Lib\SocketServer.py", line 334, in finish_request
ERROR:     self.RequestHandlerClass(request, client_address, self)
ERROR:   File "C:\Kodi\Kodi-15-Isengard\system\python\Lib\SocketServer.py", line 651, in __init__
ERROR:     self.handle()
ERROR:   File "C:\Kodi\Kodi-15-Isengard\system\python\Lib\BaseHTTPServer.py", line 340, in handle
ERROR:     self.handle_one_request()
ERROR:   File "C:\Kodi\Kodi-15-Isengard\system\python\Lib\BaseHTTPServer.py", line 328, in handle_one_request
ERROR:     method()
ERROR:   File "C:\Kodi\Kodi-15-Isengard\portable_data\addons\script.sonos\resources\lib\soco\events.py", line 230, in do_NOTIFY
ERROR:     variables = parse_event_xml(content)
ERROR:   File "C:\Kodi\Kodi-15-Isengard\portable_data\addons\script.sonos\resources\lib\soco\events.py", line 136, in parse_event_xml
ERROR:     value = from_didl_string(value)[0]
ERROR:   File "C:\Kodi\Kodi-15-Isengard\portable_data\addons\script.sonos\resources\lib\soco\data_structures.py", line 78, in from_didl_string
ERROR:     items.append(cls.from_element(elt))
ERROR:   File "C:\Kodi\Kodi-15-Isengard\portable_data\addons\script.sonos\resources\lib\soco\data_structures.py", line 370, in from_element
ERROR:     raise DIDLMetadataError("Missing id attribute")
ERROR: DIDLMetadataError: Missing id attribute
```

From the message:

```
Event content: <e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0"><e:property><LastChange>&lt;Event xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/AVT/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;&lt;InstanceID val=&quot;0&quot;&gt;&lt;TransportState val=&quot;STOPPED&quot;/&gt;&lt;CurrentPlayMode val=&quot;SHUFFLE_NOREPEAT&quot;/&gt;&lt;CurrentCrossfadeMode val=&quot;0&quot;/&gt;&lt;NumberOfTracks val=&quot;8539&quot;/&gt;&lt;CurrentTrack val=&quot;2&quot;/&gt;&lt;CurrentSection val=&quot;0&quot;/&gt;&lt;CurrentTrackURI val=&quot;x-file-cifs://192.168.0.3/Music/Various%20Artists/Various%20Comedy%20Songs/03%20-%20A%20Tribe%20Of%20Toffs%20-%20John%20Ketley%20Is%20A%20Weatherman.mp3&quot;/&gt;&lt;CurrentTrackDuration val=&quot;0:03:20&quot;/&gt;&lt;CurrentTrackMetaData val=&quot;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;-1&amp;quot; parentID=&amp;quot;-1&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;res protocolInfo=&amp;quot;x-file-cifs:*:audio/mpeg:*&amp;quot; duration=&amp;quot;0:03:20&amp;quot;&amp;gt;x-file-cifs://192.168.0.3/Music/Various%20Artists/Various%20Comedy%20Songs/03%20-%20A%20Tribe%20Of%20Toffs%20-%20John%20Ketley%20Is%20A%20Weatherman.mp3&amp;lt;/res&amp;gt;&amp;lt;r:streamContent&amp;gt;&amp;lt;/r:streamContent&amp;gt;&amp;lt;r:radioShowMd&amp;gt;&amp;lt;/r:radioShowMd&amp;gt;&amp;lt;upnp:albumArtURI&amp;gt;/getaa?u=x-file-cifs%3a%2f%2f192.168.0.3%2fMusic%2fVarious%2520Artists%2fVarious%2520Comedy%2520Songs%2f03%2520-%2520A%2520Tribe%2520Of%2520Toffs%2520-%2520John%2520Ketley%2520Is%2520A%2520Weatherman.mp3&amp;amp;amp;v=4&amp;lt;/upnp:albumArtURI&amp;gt;&amp;lt;dc:title&amp;gt;John Ketley Is A Weatherman&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioItem.musicTrack&amp;lt;/upnp:class&amp;gt;&amp;lt;dc:creator&amp;gt;A Tribe Of Toffs&amp;lt;/dc:creator&amp;gt;&amp;lt;upnp:album&amp;gt;Various Comedy Songs&amp;lt;/upnp:album&amp;gt;&amp;lt;upnp:originalTrackNumber&amp;gt;3&amp;lt;/upnp:originalTrackNumber&amp;gt;&amp;lt;r:albumArtist&amp;gt;A Tribe Of Toffs&amp;lt;/r:albumArtist&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&quot;/&gt;&lt;r:NextTrackURI val=&quot;x-file-cifs://192.168.0.3/Music/FLAC/Placebo/Meds/10%20-%20Broken%20Promise%20(feat.%20Michael%20Stipe).flac&quot;/&gt;&lt;r:NextTrackMetaData val=&quot;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;-1&amp;quot; parentID=&amp;quot;-1&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;res protocolInfo=&amp;quot;x-file-cifs:*:audio/flac:*&amp;quot; duration=&amp;quot;0:04:12&amp;quot;&amp;gt;x-file-cifs://192.168.0.3/Music/FLAC/Placebo/Meds/10%20-%20Broken%20Promise%20(feat.%20Michael%20Stipe).flac&amp;lt;/res&amp;gt;&amp;lt;upnp:albumArtURI&amp;gt;/getaa?u=x-file-cifs%3a%2f%2f192.168.0.3%2fMusic%2fFLAC%2fPlacebo%2fMeds%2f10%2520-%2520Broken%2520Promise%2520(feat.%2520Michael%2520Stipe).flac&amp;amp;amp;v=4&amp;lt;/upnp:albumArtURI&amp;gt;&amp;lt;dc:title&amp;gt;Broken Promise (feat. Michael Stipe)&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioItem.musicTrack&amp;lt;/upnp:class&amp;gt;&amp;lt;dc:creator&amp;gt;Placebo&amp;lt;/dc:creator&amp;gt;&amp;lt;upnp:album&amp;gt;Meds&amp;lt;/upnp:album&amp;gt;&amp;lt;upnp:originalTrackNumber&amp;gt;10&amp;lt;/upnp:originalTrackNumber&amp;gt;&amp;lt;r:albumArtist&amp;gt;Placebo&amp;lt;/r:albumArtist&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&quot;/&gt;&lt;r:EnqueuedTransportURI val=&quot;x-file-cifs://192.168.0.3/Music/Various%20Artists/Various%20Comedy%20Songs/03%20-%20A%20Tribe%20Of%20Toffs%20-%20John%20Ketley%20Is%20A%20Weatherman.mp3&quot;/&gt;&lt;r:EnqueuedTransportURIMetaData val=&quot;&amp;lt;DIDL-Lite xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot; xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;&amp;quot; parentID=&amp;quot;&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title /&amp;gt;&amp;lt;res protocolInfo=&amp;quot;x-rincon-playlist:*:*:*&amp;quot;&amp;gt;x-file-cifs://192.168.0.3/Music/Various%20Artists/Various%20Comedy%20Songs/03%20-%20A%20Tribe%20Of%20Toffs%20-%20John%20Ketley%20Is%20A%20Weatherman.mp3&amp;lt;/res&amp;gt;&amp;lt;upnp:class&amp;gt;object&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;RINCON_AssociatedZPUDN&amp;lt;/desc&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&quot;/&gt;&lt;PlaybackStorageMedium val=&quot;NETWORK&quot;/&gt;&lt;AVTransportURI val=&quot;x-rincon-queue:RINCON_000E58C8FC4601400#0&quot;/&gt;&lt;AVTransportURIMetaData val=&quot;&quot;/&gt;&lt;NextAVTransportURI val=&quot;&quot;/&gt;&lt;NextAVTransportURIMetaData val=&quot;&quot;/&gt;&lt;CurrentTransportActions val=&quot;Set, Play, Stop, Pause, Seek, Next, Previous&quot;/&gt;&lt;r:CurrentValidPlayModes val=&quot;SHUFFLE,REPEAT,CROSSFADE&quot;/&gt;&lt;r:MuseSessions val=&quot;&quot;/&gt;&lt;TransportStatus val=&quot;OK&quot;/&gt;&lt;r:SleepTimerGeneration val=&quot;0&quot;/&gt;&lt;r:AlarmRunning val=&quot;0&quot;/&gt;&lt;r:SnoozeRunning val=&quot;0&quot;/&gt;&lt;r:RestartPending val=&quot;0&quot;/&gt;&lt;TransportPlaySpeed val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;CurrentMediaDuration val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;RecordStorageMedium val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;PossiblePlaybackStorageMedia val=&quot;NONE, NETWORK&quot;/&gt;&lt;PossibleRecordStorageMedia val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;RecordMediumWriteStatus val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;CurrentRecordQualityMode val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;PossibleRecordQualityModes val=&quot;NOT_IMPLEMENTED&quot;/&gt;&lt;/InstanceID&gt;&lt;/Event&gt;</LastChange></e:property></e:propertyset>
```

**Comment by robwebset** [comment]
Not seen this error for a little while - so closing this as fixed.
