### ISSUE TITLE
Can't simultaneously run soco.events.event_listener in two separate applications

### ISSUE THREAD

**Issue by relevitt** [SoCo/SoCo#379]
Using soco 0.11.1 installed via pip. 

First application has the following module ...

```
# -*- coding: utf-8 -*- 

from soco.events import event_listener
from Queue import Empty

from twisted.internet import reactor
from twisted.internet import threads
from twisted.internet.defer import inlineCallbacks

from error import *

# event_notifier - sets up event loops for a device

class event_notifier():

	def __init__(self, factory, device):
		self.factory = factory
		self.device = device
		self.sub1 = device.renderingControl.subscribe()
		self.sub2 = device.avTransport.subscribe()
		reactor.callWhenRunning(self.startup1)
		reactor.callWhenRunning(self.startup2)
		reactor.addSystemEventTrigger('before', 'shutdown', self.cleanup)

	def cleanup(self):
		print self.device.uid, 'shutting down event notifers'
		self.sub1.unsubscribe()
		self.sub2.unsubscribe()
		event_listener.stop()

	def reset(self):
		self.sub2.unsubscribe()
		self.sub2 = self.device.avTransport.subscribe()

	def checkit1(self):
		def cb():
			## The timeout can be as long as you like, but the reactor won't shutdown until
			## an event is received or the timeout expires (expiry triggers an 'Empty' event)
			try:
				event = self.sub1.events.get(timeout=1)
				try:
					return event.variables['volume']['Master']
				except:
					print 'volume event error'
			except Empty:
				pass
		d = threads.deferToThread(cb)
		d.addErrback(printError)
		return d

	def checkit2(self):
		def cb():
			try:
				event = self.sub2.events.get(timeout=1)
				return event.variables
			except Empty:
				pass
		d = threads.deferToThread(cb)
		d.addErrback(printError)
		return d

	@inlineCallbacks
	def startup1(self):
		while True:
			result = yield self.checkit1()
			if result != None:
				self.factory.WS_volume(self.device.group.uid, self.device.uid, result)

	@inlineCallbacks
	def startup2(self):
		while True:
			result = yield self.checkit2()
			if result:
				if self.device.is_coordinator:
					self.factory.avTransportEvent(self.device.group.uid, result)
```

Second application has the following code ...

```
# -*- coding: utf-8 -*- 

import sys
sys.dont_write_bytecode = True
from pprint import pprint
from Queue import Empty

import soco

device = list(soco.discover())[0]
group = device.group
device = group.coordinator

service = soco.services.GroupManagement(device)

sub = service.subscribe()

while True:
	try:
		event = sub.events.get(timeout=1)
		if event.variables:
			pprint(event.variables)

	except Empty:
		pass

```

If the second application is run while the first application is running, the first application reports the following errors ...

```
----------------------------------------
Exception happened during processing of request from ('192.168.1.86', 34931)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/dist-packages/soco/events.py", line 228, in do_NOTIFY
    service.service_id, threading.current_thread(), timestamp)
AttributeError: 'NoneType' object has no attribute 'service_id'
----------------------------------------
```

while the second application reports the following error ...

```
$ python soco_test.py 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/soco/events.py", line 266, in run
    listener = EventServer(self.address, EventNotifyHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

```

**Comment by cassieramen** [comment]
Not sure if you're still having this issue. The event listener is actually running a simply http server that the sonos is sending notification to. Running two with cause the port collision you're seeing. I'd highly recommend having one listener that dispatches the notification to the appropriate handler.

If you must have two running you can alter [soco.config.EVENT_LISTENER_PORT](http://docs.python-soco.com/en/latest/api/soco.events.html?highlight=event_listener_port). By default it's set to 1400.

```
import soco
soco.config.EVENT_LISTENER_PORT=8080
````

**Comment by relevitt** [comment]
Thanks.
