### ISSUE TITLE
party_mode doesn't work

### ISSUE THREAD

**Issue by pmatos** [SoCo/SoCo#394]
So, `party_mode()` doesn't actually do party mode. 

For example:
A group of three speakers:
```
>>> t.group
ZoneGroup(uid='RINCON_000E5873C77601400:36', coordinator=SoCo("192.168.178.136"), members={SoCo("192.168.178.168"), SoCo("192.168.178.136"), SoCo("192.168.178.135")})
```

Then we try `party_mode()` and I expected all to stay the same since I currently only have 3 speakers in the network but:
```
>>> t.partymode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pmatos/Projects/SoCo/soco/core.py", line 871, in partymode
    [zone.join(self) for zone in self.visible_zones if zone is not self]
  File "/home/pmatos/Projects/SoCo/soco/core.py", line 871, in <listcomp>
    [zone.join(self) for zone in self.visible_zones if zone is not self]
  File "/home/pmatos/Projects/SoCo/soco/core.py", line 883, in join
    ('CurrentURIMetaData', '')
  File "/home/pmatos/Projects/SoCo/soco/services.py", line 181, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/home/pmatos/Projects/SoCo/soco/services.py", line 397, in send_command
    self.handle_upnp_error(response.text)
  File "/home/pmatos/Projects/SoCo/soco/services.py", line 458, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 501 received: Action Failed from 192.168.178.168

```
I can however unjoin and try `party_mode()` but:
```
>>> t.unjoin()
>>> t.partymode()
>>> t.group
ZoneGroup(uid='RINCON_B8E937B17E6201400:3', coordinator=SoCo("192.168.178.135"), members={SoCo("192.168.178.136"), SoCo("192.168.178.135")})
```

Party mode now only joins me to one other speaker. Not all of them. How can I achieve real party mode? How can I manipulate groups?

**Comment by KennethNielsen** [comment]
@pmatos wow this has been sitting here for a while. Can you confirm whether this is still an issue?

**Comment by zeiv** [comment]
I can confirm.  In my particular case, if all zones are already in the same group I get the UPnP error above.  Unjoining and then trying partymode again works.  I have not tested this there the zone I am calling partymode on is in a group that contains more than one but less than the total number of zones.
