### ISSUE TITLE
Playing/Queuing music_service items results in UPNP errors

### ISSUE THREAD

**Issue by benlm54** [SoCo/SoCo#405]
I can't for the life of me figure out how to play items I find in music services. I have tried TuneIn, Slacker, and iHeartRadio.

Here are two scripts that demonstrate different approaches I have taken and both result in different UPNP errors.

Am I doing it wrong, or is it even possible to play or queue-up music service items using soco?

[tunein_test1.py.txt](https://github.com/SoCo/SoCo/files/308236/tunein_test1.py.txt)
[tunein_test2.py.txt](https://github.com/SoCo/SoCo/files/308237/tunein_test2.py.txt)

**Comment by lawrenceakka** [comment]
1) You can't add a radio station to the queue, so add_to_queue will never work

2) play_uri is closer, but is really designed to play arbitrary streaming uris, not music service items

3) There is currently no easy function to play a stream from a music service (as opposed to a track or album). Generating a streaming uri using some modification of sonos_uri_from_id might do it, but you'd have to dig out wireshark and see what is going on when the official controllers play a stream

I'll add this to the list of things to look at 😉

**Comment by lawrenceakka** [comment]
OK, this seems to work (at least with TuneIn). Let me know if it works with the others:

```python
from __future__ import unicode_literals
from soco import SoCo
from soco.music_services import MusicService
from soco.data_structures import DidlItem, to_didl_string
from soco.compat import quote_url

device = SoCo('192.168.1.123')  # Replace with IP address of your sonos
service = MusicService('TuneIn')
item_id = "s270109"
item_id = quote_url(item_id.encode('utf-8'))

account = service.account
uri = "x-sonosapi-stream:{0}?sid={1}&sn={2}".format(
    item_id, service.service_id, account.serial_number)

didl = DidlItem(
    title="DUMMY", parent_id="DUMMY",item_id="DUMMY", desc=service.desc)
meta = to_didl_string(didl)


device.avTransport.SetAVTransportURI(
    [('InstanceID', 0), ('CurrentURI', uri), ('CurrentURIMetaData', meta)])
device.play()
```

**Comment by benlm54** [comment]
Thanks! I'll do some testing with different streams and services using this method and report results back here.

**Comment by benlm54** [comment]
I tested this approach with Slacker radio. It did not work, but after capturing some packets with Wireshark I was able to get the right URI. Here is a script that plays a Slacker radio item.

[slacker_test.py.txt](https://github.com/SoCo/SoCo/files/310015/slacker_test.py.txt)

**Comment by tksunw** [comment]
The code above from @lawrenceakka works with SiriusXM, Pandora, and Calm Radio channels that are in the Sonos Favorites list, as enumerated by either `PLAYER.music_library.get_sonos_favorites()` or `PLAYER.get_sonos_favorites()`


Example URIs for each service, as stored in the Sonos Favorites:

Sirius XM: `'x-sonosapi-hls:live%3a9450?sid=37&flags=8480&sn=4'`

Pandora: `'x-sonosapi-radio:ST:3493649015737010677?sid=236&flags=8300&sn=1'`

Calm Radio: `'x-sonosapi-stream:stream%3a9%3a320?sid=144&flags=8224&sn=3'`

Calling `PLAYER.play_uri(uri)` with these SiriusXM and Calm Radio URIs doesn't work.    `PLAYER.play_uri(uri)` *does* work with the Pandora URIs, though.

```
>>> uri = 'x-sonosapi-hls:live%3a9450?sid=37&flags=8480&sn=4'
>>> PLAYER.play_uri(uri)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/soco/core.py", line 106, in inner_function
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/soco/core.py", line 591, in play_uri
    ('CurrentURIMetaData', meta)
  File "/usr/local/lib/python3.6/dist-packages/soco/services.py", line 213, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/soco/services.py", line 498, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/local/lib/python3.6/dist-packages/soco/services.py", line 560, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 402 received: Invalid Args from 192.168.1.66

```

However, creating the DUMMY `DidlItem` and `meta` string, and using `PLAYER.avTransport.SetAVTransportURI()` does work.

```
>>> didl = DidlItem(title="DUMMY", parent_id="DUMMY",item_id="DUMMY", desc='DUMMY')
>>> meta = to_didl_string(didl)
>>> PLAYER.avTransport.SetAVTransportURI([('InstanceID', 0), ('CurrentURI', uri), ('CurrentURIMetaData', meta)])
True
>>> PLAYER.play()
>>> PLAYER.get_current_track_info()
{'title': 'x-sonosapi-hls:live:9450?sid=37&flags=8480&sn=4', 'artist': '', 'album': '', 'album_art': '', 'position': '0:00:05', 'playlist_position': '1', 'duration': '0:00:00', 'uri': 'x-sonosapi-hls:live%3a9450?sid=37&flags=8480&sn=4', 'metadata': '<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="-1" parentID="-1" restricted="true"><res protocolInfo="sonos.com-http:*:application/x-mpegURL:*">x-sonosapi-hls:live%3a9450?sid=37&amp;flags=8480&amp;sn=4</res><r:streamContent>BR P|TYPE=SNG|TITLE If You Could Only See (97)|ARTIST Tonic|ALBUM </r:streamContent><upnp:albumArtURI>http://albumart.siriusxm.com/albumart/2200/NDCA-000061664-002_m.jpg</upnp:albumArtURI><dc:title>x-sonosapi-hls:live:9450?sid=37&amp;flags=8480&amp;sn=4</dc:title><upnp:class>object.item.audioItem.musicTrack</upnp:class></item></DIDL-Lite>'}
```

I did read in the docs that `play_uri()` is only for unauthenticated URIs, but I don't have any issues playing URIs via the `SetAVTransportURI()` method.  Although, `MusicServices` seems to be entirely unaware of any service subscriptions, it doesn't seem to interfere with being able to play URIs from subscription services.

```
>>> MusicService.get_all_music_services_names()
['Radio.com', 'Global Player', 'Apple Music', 'Triple M', 'SoundCloud', 'Audible', 'Spotify', 'Pandora', 'Napster', 'Google Play Music', 'NRK Radio', 'CBC Radio & Music', 'Amazon Music', 'Hit Network', 'Relisten', 'ARTRADIO - RadioArt.com', 'WEYV', 'My Cloud Home', 'Worldwide FM', 'Plex', 'iHeartRadio', 'myTuner Radio', 'nugs.net', 'LivePhish+', 'PowerApp', 'radio.net', 'Canopy', 'Sveriges Radio', 'Minidisco', 'NTS Radio', 'TIDAL', '企鹅FM', 'Radio Disney', 'storePlay', 'Stitcher SmartRadio', 'SiriusXM', 'deliver.media', 'Saavn', 'Pocket Casts', 'TuneIn', "Wolfgang's Music", 'AccuRadio', 'Deezer', 'Bandcamp', 'focus@will', 'RauteMusik.FM', 'Audiobooks.com', 'Murfie', 'Stingray Music', 'FIT Radio Workout Music', 'radioPup', 'Mixcloud', 'Hype Machine', '7digital', 'Anghami', 'SOUNDMACHINE', 'Custom Channels', 'Dash Radio', 'Rockbot', 'NhacCuaTui', 'Tribe of Noise', 'Slacker', 'Mood Mix', 'Classical Archives', 'Gaana', 'Spreaker', 'Radionomy', 'RUSC', 'Calm Radio', 'hotelradio.fm', 'Hearts of Space', 'DAR.fm Record Radio']
>>> MusicService.get_subscribed_services_names()
[]
````

**Comment by rr326** [comment]
For any finding this thread who want a workaround (based on the above information).

Tested with soco 0.29.0, on 1/26/23, with SiriusXM

```
# 1. First save your radio station (or whatever) as a  **Sonos Favorite**

# 2. Get a player
player=soco.discovery.by_name("MySonosPlayerName")

# 3. Print your favorites
print(favorites := player.get_sonos_favorites())

# 4. Select your favorite
fav=favorites['favorites'][0]

#5. Play it!
player.play_uri(uri=fav["uri"], meta=fav["meta"])


```
