### ISSUE TITLE
discover() raises Cannot assign requested address

### ISSUE THREAD

**Issue by agriffis** [SoCo/SoCo#431]
I'm seeing this on master:

```
$ python3 -c 'import soco; soco.discover()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aron/src/ss/sonos/SoCo/soco/discovery.py", line 114, in discover
    _sockets.append(create_socket(address))
  File "/home/aron/src/ss/sonos/SoCo/soco/discovery.py", line 77, in create_socket
    socket.inet_aton(interface_addr))
OSError: [Errno 99] Cannot assign requested address
```

Bisecting shows the problem was introduced by dfda28558cd571feeaa64367d126823d9a09f3db

```
$ git bisect start master v0.11.1                                                                                                                                                              
Bisecting: 94 revisions left to test after this (roughly 7 steps)
[d6002ec236ad1a44e7335586db8b9c019492983e] Travis: Disable pylint on 2,6, enable 3.4, general pylint cleanup

$ git bisect run python3 -c 'import soco; soco.discover()'
running python3 -c import soco; soco.discover()
Bisecting: 47 revisions left to test after this (roughly 6 steps)
[8862b5d7441dad7b229f1f71315ce0c5ec9fad92] Add filtering of illegal XML chars on parse error in unwrap_arguments, fixes #386
running python3 -c import soco; soco.discover()
Bisecting: 23 revisions left to test after this (roughly 5 steps)
[5b5eb191eb8bf513fa10c7c6cf2dcc4260fa0021] Correct mute error in readme. Closes #416
running python3 -c import soco; soco.discover()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aron/src/ss/sonos/SoCo/soco/discovery.py", line 115, in discover
    _sockets.append(create_socket(address))
  File "/home/aron/src/ss/sonos/SoCo/soco/discovery.py", line 77, in create_socket
    socket.inet_aton(interface_addr))
OSError: [Errno 99] Cannot assign requested address
Bisecting: 11 revisions left to test after this (roughly 4 steps)
[585437d9a998d04e13172996896ac2195df0f376] Convert bytestring returned by XML generation for SOAP header
running python3 -c import soco; soco.discover()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aron/src/ss/sonos/SoCo/soco/discovery.py", line 114, in discover
    _sockets.append(create_socket(address))
  File "/home/aron/src/ss/sonos/SoCo/soco/discovery.py", line 77, in create_socket
    socket.inet_aton(interface_addr))
OSError: [Errno 99] Cannot assign requested address
Bisecting: 5 revisions left to test after this (roughly 3 steps)
[4ea75acaec66e394e2c55600de015ef3f43273e9] A few style changes: Closes #292
running python3 -c import soco; soco.discover()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aron/src/ss/sonos/SoCo/soco/discovery.py", line 114, in discover
    _sockets.append(create_socket(address))
  File "/home/aron/src/ss/sonos/SoCo/soco/discovery.py", line 77, in create_socket
    socket.inet_aton(interface_addr))
OSError: [Errno 99] Cannot assign requested address
Bisecting: 2 revisions left to test after this (roughly 2 steps)
[4896e794b6fb90353b99f81dc09a3ee172b7efc5] And another Python 2.6 fix; ElemenTree < python 2.7 raised SyntaxError instead of ParseError on bad chars
running python3 -c import soco; soco.discover()
Bisecting: 0 revisions left to test after this (roughly 1 step)
[dfda28558cd571feeaa64367d126823d9a09f3db] More aggresssive discovery - thanks @robwebset. Closes #289
running python3 -c import soco; soco.discover()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aron/src/ss/sonos/SoCo/soco/discovery.py", line 114, in discover
    _sockets.append(create_socket(address))
  File "/home/aron/src/ss/sonos/SoCo/soco/discovery.py", line 77, in create_socket
    socket.inet_aton(interface_addr))
OSError: [Errno 99] Cannot assign requested address
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[8e868a065dbb2c370df47fb8247ca9af1bee7155] Merge pull request #392 from KennethNielsen/filter_invalid_chars_in_xml_fixes
running python3 -c import soco; soco.discover()
dfda28558cd571feeaa64367d126823d9a09f3db is the first bad commit
commit dfda28558cd571feeaa64367d126823d9a09f3db
Author: Lawrence Akka <lakka@fake.email>
Date:   Wed May 11 15:26:05 2016 +0100

    More aggresssive discovery - thanks @robwebset. Closes #289

:040000 040000 5ba40c8f037ef17b632a55f2b8a3aba6908eef96 b2a163595c12d499754a25c8dde53c4b426bceee M      soco
:040000 040000 a32ee506834f8bae6ece5401114c9f75d2823a52 d3a8793c24defdbb0d0895f1751acdeb7e59ea6c M      tests
bisect run success
```

**Comment by KennethNielsen** [comment]
Nice work on the bi-sectioning. Just out of curiosity, what version of Python are you using?

**Comment by agriffis** [comment]
@KennethNielsen Python 3.5.2 on Fedora 25

**Comment by KennethNielsen** [comment]
Ok. I guess we can conclude that the Pyhon3 use base for SoCo is not as big as a I had hoped.

**Comment by agriffis** [comment]
@KennethNielsen what makes you say that? This doesn't seem related to Python 3

**Comment by KennethNielsen** [comment]
Ahh yes. Sorry. I must have been tired. I was just wondering why we hadn't seen this issue earlier, but that is of course because it was triggered by a special DNS conf.
