### ISSUE TITLE
MusicServiceException trying to access Google Play

### ISSUE THREAD

**Issue by agriffis** [SoCo/SoCo#433]
It seems I can't access Google Play, either with `get_metadata` or `search`. They both raise `MusicServiceException`:

```
In [1]: from soco.music_services import MusicService
In [2]: gp = MusicService('Google Play Music')
In [3]: gp.get_metadata()
---------------------------------------------------------------------------
SoapFault                                 Traceback (most recent call last)
soco/music_services/music_service.py in call(self, method, args)
    150         try:
--> 151             result_elt = message.call()
    152         except SoapFault as exc:

soco/soap.py in call(self)
    309             faultdetail = fault.find("detail")
--> 310             raise SoapFault(faultcode, faultstring, faultdetail)
    311         else:

SoapFault: soap:Client: Invalid credentials in request.

During handling of the above exception, another exception occurred:

MusicServiceException                     Traceback (most recent call last)
<ipython-input-3-3e168d6ad5d8> in <module>()
----> 1 gp.get_metadata()

soco/music_services/music_service.py in get_metadata(self, item_id, index, count, recursive)
    680                 ('id', item_id),
    681                 ('index', index), ('count', count),
--> 682                 ('recursive', 1 if recursive else 0)]
    683         )
    684         return response.get('getMetadataResult', None)

soco/music_services/music_service.py in call(self, method, args)
    180 
    181             else:
--> 182                 raise MusicServiceException(exc.faultstring, exc.faultcode)
    183 
    184         # The top key in the OrderedDict will be the methodResult. Its

MusicServiceException: ('Invalid credentials in request.', 'soap:Client')
```

Trying to search yields the same result.

Is this an expected error with the current progress of the music services code?

**Comment by agriffis** [comment]
Very similar result trying to access Amazon

```
In [13]: a = MusicService('Amazon Music')

In [14]: a.get_metadata()
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-14-70d36d9e2e2f> in <module>()
----> 1 a.get_metadata()

/home/aron/.virtualenvs/sonos/src/soco/soco/music_services/music_service.py in get_metadata(self, item_id, index, count, recursive)
    680                 ('id', item_id),
    681                 ('index', index), ('count', count),
--> 682                 ('recursive', 1 if recursive else 0)]
    683         )
    684         return response.get('getMetadataResult', None)

/home/aron/.virtualenvs/sonos/src/soco/soco/music_services/music_service.py in call(self, method, args)
    149 
    150         try:
--> 151             result_elt = message.call()
    152         except SoapFault as exc:
    153             if 'Client.TokenRefreshRequired' in exc.faultcode:

/home/aron/.virtualenvs/sonos/src/soco/soco/soap.py in call(self)
    312             # Something else has gone wrong. Probably a network error. Let
    313             # Requests handle it
--> 314             response.raise_for_status()

/home/aron/.virtualenvs/sonos/lib/python3.5/site-packages/requests/models.py in raise_for_status(self)
    860 
    861         if http_error_msg:
--> 862             raise HTTPError(http_error_msg, response=self)
    863 
    864     def close(self):

HTTPError: 403 Client Error: Forbidden for url: https://sonos.amazonmusic.com/
```

**Comment by agriffis** [comment]
Bandcamp just returns None for both tests:

```
In [15]: bc = MusicService('Bandcamp')

In [16]: bc.get_metadata()

In [17]: bc.search('artists', 'All India Radio')

```

**Comment by agriffis** [comment]
The only other service to which I'm subscribed is TuneIn, and it responds properly to both `get_metdata` and `search`

**Comment by KennethNielsen** [comment]
I don't think this is an expected error.

@lawrenceakka do you have some time to look into this?

**Comment by Khanivore** [comment]
I'm trying to access Amazon Music and having the same issue. I can talk to Amazon Music as follows:

```
>>> print(amazonMusic.available_search_categories)
dict_keys(['albums', 'artists', 'stations', 'tracks', 'playlists'])

```
But when I try to search I get the 403 error (please note i removed some error lines and left the important one at the end:

```
>>> print(amazonMusic.search('albums',term='Nation',index=0,count=100))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
```
.
. (removed some python error lines)
.
```
line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sonos.amazonmusic.com/

```

**Comment by KennethNielsen** [comment]
Thanks for reporting this. I don't know if @lawrenceakka has the time to look at this, otherwise I will give it a shot when I find the time.

**Comment by Khanivore** [comment]
Please be aware this could be 'user error'. I'm a coding newbie :) Before expending effort on it please do make sure I've not made a silly mistake.

**Comment by KennethNielsen** [comment]
@Khanivore to check that you will need to post a complete runnable code example. However, we seem to be seeing a pattern here, so I do not think it is user error ;)

**Comment by leanto** [comment]
I'm having similar issues. Here's how to repro the problem:
```shell
$ PYTHONPATH=$HOME/Projects/SoCo python3                                                             
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from soco.music_services import MusicService
>>> google=MusicService("Google Play Music")
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> google.search('tracks')
INFO:soco.music_services.music_service:Fetching presentation map from https://www.gstatic.com/play/music/sonosfe/pmap.xml
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.gstatic.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /play/music/sonosfe/pmap.xml HTTP/1.1" 200 1279
DEBUG:soco.services:Dispatching method GetHouseholdID
INFO:soco.services:Sending GetHouseholdID None to 192.168.1.58
DEBUG:soco.services:Sending {'Content-Type': 'text/xml; charset="utf-8"', 'SOAPACTION': 'urn:schemas-upnp-org:service:DeviceProperties:1#GetHouseholdID'}, <?xml version="1.0" ?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Body>
    <u:GetHouseholdID xmlns:u="urn:schemas-upnp-org:service:DeviceProperties:1"/>
  </s:Body>
</s:Envelope>

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.58
DEBUG:requests.packages.urllib3.connectionpool:"POST /DeviceProperties/Control HTTP/1.1" 200 338
DEBUG:soco.services:Received {'Server': 'Linux UPnP/1.0 Sonos/33.15-32291 (ZPS6)', 'CONTENT-LENGTH': '338', 'Connection': 'close', 'EXT': '', 'CONTENT-TYPE': 'text/xml; charset="utf-8"'}, <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetHouseholdIDResponse xmlns:u="urn:schemas-upnp-org:service:DeviceProperties:1"><CurrentHouseholdID>Sonos_fIP12jz0rJCE7qhWcNojPj3tR4</CurrentHouseholdID></u:GetHouseholdIDResponse></s:Body></s:Envelope>
INFO:soco.services:Received status 200 from 192.168.1.58
DEBUG:soco.soap:Sending {'Content-Type': 'text/xml; charset="utf-8"', 'User-Agent': 'Linux UPnP/1.0 Sonos/26.99-12345', 
'SOAPACTION': '"http://www.sonos.com/Services/1.1#search"', 'Accept-Encoding': 'gzip, deflate'}, <?xml version="1.0" ?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <credentials xmlns="http://www.sonos.com/Services/1.1">
      <deviceId>5C-AA-FD-02-21-E0:2</deviceId>
      <deviceProvider>Sonos</deviceProvider>
      <loginToken>
        <token>Sonos_REDACTED</token>
        <key/>
        <householdId>Sonos_REDACTED</householdId>
      </loginToken>
    </credentials>
  </s:Header>
  <s:Body>
    <search xmlns="http://www.sonos.com/Services/1.1">
      <id>TRACK</id>
      <term/>
      <index>0</index>
      <count>100</count>
    </search>
  </s:Body>
</s:Envelope>

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): mclients.googleapis.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /music/sonos/wsf/smapi HTTP/1.1" 500 None
DEBUG:soco.soap:Received {'Content-Type': 'text/xml; charset=UTF-8', 'Server': 'GSE', 'Expires': 'Wed, 26 Oct 2016 20:2$:01 GMT', 'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'private, max-age=0', 'Alt-Svc': 'quic=":443"; ma=2592000; v="36,35,34"', 'Content-Encoding': 'gzip', 'X-XSS-Protection': '1; mode=block', 'X-Frame-Options': 'SAMEORIGIN', 'Transfer-Encoding': 'chunked', 'Date': 'Wed, 26 Oct 2016 20:29:01 GMT'}, <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>Invalid credentials in request.</faultstring><detail><ExceptionInfo>Invalid credentials in request.</ExceptionInfo><SonosError>16</SonosError></detail
></soap:Fault></soap:Body></soap:Envelope>
Traceback (most recent call last):
  File "/home/flan/Projects/SoCo/soco/music_services/music_service.py", line 151, in call
    result_elt = message.call()
  File "/home/flan/Projects/SoCo/soco/soap.py", line 310, in call
    raise SoapFault(faultcode, faultstring, faultdetail)
soco.soap.SoapFault: soap:Client: Invalid credentials in request.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/flan/Projects/SoCo/soco/music_services/music_service.py", line 715, in search
    ('count', count)])
  File "/home/flan/Projects/SoCo/soco/music_services/music_service.py", line 182, in call
    raise MusicServiceException(exc.faultstring, exc.faultcode)
soco.exceptions.MusicServiceException: ('Invalid credentials in request.', 'soap:Client')
```

**Comment by lawrenceakka** [comment]
I am (belatedly) having a look at this. Google Play has always been a bit fussy.

**Comment by KennethNielsen** [comment]
Hi @lawrenceakka and thanks.

I think there must be some fundamental change at play here, since we are getting these authentication related issue for many services: Google Play, Amazon Music and Bandcamp in this issue and Spotify in #428.

**Comment by Guimcha** [comment]
Hi!
Thank you for this great library.
I encounter the same error as others : Invalid credentials in request trying to search for something in Google Play MusicService.
Do you have any clue on what is going on ?
Guimcha

**Comment by ghcs27** [comment]
Here's what's going on:

> **lawrenceakka** [commented on issue 428](https://github.com/SoCo/SoCo/issues/428#issuecomment-289300915):
> Sonos has changed the way in which music service account data can be accessed. It used to be possible to get the necessary info from the players, but it is now encrypted using AES-CBC. Although other third party Sonos controllers have worked out how to get round this and decrypt the info (see here for a discussion), I am not sure that it would be right for us to do so in an open source project (though I haven't decided yet).

**Comment by Guimcha** [comment]
Thank you
althought @lawrenceakka managed to make soco work with google with user interaction (OAuth login?). do you think it may be possible to do the same easily ?

**Comment by ghcs27** [comment]
Sorry, you'd have to ask @lawrenceakka directly - I don't know how he did the user login.

**Comment by KennethNielsen** [comment]
Closing this issue in favor of #557 to gather information in one place.
