### ISSUE TITLE
get_subscribed_services_names raises 'pop from an empty set' error

### ISSUE THREAD

**Issue by pward123** [SoCo/SoCo#451]
With soco==0.12, running the following script fails when I comment out the `device = ` line

```
from soco import SoCo
from soco.music_services import MusicService

# Commenting out the following line causes an exception
device = SoCo("192.168.1.1")
print(MusicService.get_subscribed_services_names())
```

**Comment by pward123** [comment]
Forgot to mention that I'm on python 2.7.9

**Comment by KennethNielsen** [comment]
@pward123 Thanks for reporting this. Can you please post the full trace back as well?

**Comment by apoorv-kulkarni** [comment]
@KennethNielsen I have the same issue; here is the traceback

```
>>> print(MusicService.get_subscribed_services_names())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/soco/music_services/music_service.py", line 479, in get_subscribed_services_names
    accounts_for_service(service['ServiceType'])
  File "/usr/local/lib/python2.7/site-packages/soco/music_services/accounts.py", line 197, in get_accounts_for_service
    a for a in cls.get_accounts().values()
  File "/usr/local/lib/python2.7/site-packages/soco/music_services/accounts.py", line 104, in get_accounts
    root = XML.fromstring(cls._get_account_xml(soco))
  File "/usr/local/lib/python2.7/site-packages/soco/music_services/accounts.py", line 78, in _get_account_xml
    device = soco or discovery.any_soco()
  File "/usr/local/lib/python2.7/site-packages/soco/discovery.py", line 208, in any_soco
    return None if devices is None else devices.pop()
KeyError: 'pop from an empty set'
```

**Comment by pward123** [comment]
We ended up going a different route given that sonos seems to be moving away from allowing music service control. I'll keep this open for @apoorv-kulkarni
