### ISSUE TITLE
Illegal MIME-Type when playing Spotify playlist

### ISSUE THREAD

**Issue by jhaals** [SoCo/SoCo#477]
```python
s = get_player("Kitchen") # get player via discover
uri = s.get_sonos_favorites()['favorites'][0]['uri']
# x-rincon-cpcontainer:1006206cspotify%3auser%3aspotify%3aplaylist%3a16BpjqQV1Ey0HeDueNDSYz
s.play_uri(uri)
```

Error message
```
so.py:13: UserWarning: The output type of this method will probably change in the future to use SoCo data structures
  uri = s.get_sonos_favorites()['favorites'][0]['uri']
x-rincon-cpcontainer:1006206cspotify%3auser%3aspotify%3aplaylist%3a16BpjqQV1Ey0HeDueNDSYz
Traceback (most recent call last):
  File "so.py", line 15, in <module>
    s.play_uri(uri)
  File "/Users/jhaals/.virtualenvs/sonos/lib/python2.7/site-packages/soco/core.py", line 104, in inner_function
    return function(self, *args, **kwargs)
  File "/Users/jhaals/.virtualenvs/sonos/lib/python2.7/site-packages/soco/core.py", line 483, in play_uri
    ('CurrentURIMetaData', meta)
  File "/Users/jhaals/.virtualenvs/sonos/lib/python2.7/site-packages/soco/services.py", line 181, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/Users/jhaals/.virtualenvs/sonos/lib/python2.7/site-packages/soco/services.py", line 408, in send_command
    self.handle_upnp_error(response.text)
  File "/Users/jhaals/.virtualenvs/sonos/lib/python2.7/site-packages/soco/services.py", line 469, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 714 received: Illegal MIME-Type from 192.168.0.128
```

**Comment by jhaals** [comment]
Am I doing some obvious error in this example? The URI originates from my Sonos favourites which I can click-to-play in the Sonos app.

**Comment by KennethNielsen** [comment]
Hi @jhaals 

This is actually a frequently asked question, so I thought I would answer it once properly by adding a faq section to the docs. Here is a draft:

```rst
Why can't I play a URI from music service X with the :meth:`~soco.core.SoCo.play_uri` play_uri method?
------------------------------------------------------------------------------------------------------

The :meth:`~soco.core.SoCo.play_uri` method is only for playing URI's
with un-restricted access such as podcasts, certain radion stations or
sound clips on webpages. In short, the
:meth:`~soco.core.SoCo.play_uri` method is for anything that will play
as a sound file in your browser without authentication.

To play music from a music service, you will need to go via the
:mod:`~soco.music_services.music_service` module. Here you can search
or browse to obtain music service items, which can be added to the
queue and played.
```

Regards

**Comment by jhaals** [comment]
Thanks for the clarification Kenneth, I'll make sure give that a try instead!

**Comment by KennethNielsen** [comment]
Sure thing. You should note btw that right now the music services do not actually work, due to a change in the way they do authentication, but it is being worked on.

**Comment by jhaals** [comment]
That's very good to know otherwise I would have created yet another ticket 😄 
Is there a ticket tracking this?

**Comment by KennethNielsen** [comment]
@jhaals there are several (#446, #433, #428)
