### ISSUE TITLE
MusicService.get_metadata() failing for Google Play Music

### ISSUE THREAD

**Issue by frog32** [SoCo/SoCo#505]
get_metadata fails with the following result. If someone who understands how MusicService works can explain what it should do I would be happy to investigate further to find out why it does not work as expected.

```>>> import soco
>>> from soco.music_services import MusicService
>>> MusicService.get_subscribed_services_names()
['Google Play Music', 'TuneIn']
>>> gpm = MusicService('Google Play Music')
>>> gpm.get_metadata()
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/soco/music_services/music_service.py", line 151, in call
    result_elt = message.call()
  File "/srv/homeassistant/lib/python3.4/site-packages/soco/soap.py", line 310, in call
    raise SoapFault(faultcode, faultstring, faultdetail)
soco.soap.SoapFault: soap:Client: Invalid credentials in request.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/homeassistant/lib/python3.4/site-packages/soco/music_services/music_service.py", line 682, in get_metadata
    ('recursive', 1 if recursive else 0)]
  File "/srv/homeassistant/lib/python3.4/site-packages/soco/music_services/music_service.py", line 182, in call
    raise MusicServiceException(exc.faultstring, exc.faultcode)
soco.exceptions.MusicServiceException: ('Invalid credentials in request.', 'soap:Client')
>>> tunein = MusicService('TuneIn')
>>> tunein.get_metadata()```

**Comment by mistercormell** [comment]
I would like to echo the question raised by @frog32  - I am seeing a very similar error when trying to do the same with the Apple Music service - is this a known issue with music services of this nature?

```
>>> am = MusicService('Apple Music')
>>> am.get_metadata()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/soco/music_services/music_service.py", line 151, in call
    result_elt = message.call()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/soco/soap.py", line 310, in call
    raise SoapFault(faultcode, faultstring, faultdetail)
soco.soap.SoapFault: SOAP-ENV:Client.AuthTokenExpired: com.apple.its.commerce.sonos.resource.error.InvalidTokenException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/soco/music_services/music_service.py", line 682, in get_metadata
    ('recursive', 1 if recursive else 0)]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/soco/music_services/music_service.py", line 182, in call
    raise MusicServiceException(exc.faultstring, exc.faultcode)
soco.exceptions.MusicServiceException: ('com.apple.its.commerce.sonos.resource.error.InvalidTokenException', 'SOAP-ENV:Client.AuthTokenExpired')
```

**Comment by asebak** [comment]
Same issue I am having with the AuthTokenExpired

**Comment by mistercormell** [comment]
See here for this issue: https://github.com/SoCo/SoCo/issues/428

**Comment by KennethNielsen** [comment]
Closing this issue in favor of #557 to gather information in one place.
