### ISSUE TITLE
error when running Find_room.py 

### ISSUE THREAD

**Issue by sivakrkumar** [SoCo/SoCo#515]
Hi 
I am using python 2.7. when I tried to execute **find_room.py** in my local , it has raised the below error message. Kindly assist.

The syntax of the command is incorrect.
Traceback (most recent call last):
  File "C:\Users\siramac\Desktop\roomfinder-master\roomfinder-master\find_rooms.
py", line 57, in <module>
    rooms.update(findRooms(prefix))
  File "C:\Users\siramac\Desktop\roomfinder-master\roomfinder-master\find_rooms.
py", line 28, in findRooms
    tree = ET.fromstring(response)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1312, in XML
    return parser.close()
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1665, in close
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

**Comment by ghcs27** [comment]
From the traceback I can see that this is a parsing error in line 28 of find_rooms.py (from the *roomfinder* repository).
Since SoCo is not involved, please open an issue in the *roomfinder* repository instead.

**Comment by sivakrkumar** [comment]
still receiving same error message when running with new file. have to install any reference file..
