### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by pfischi** [SoCo/SoCo#607]
Hi all,

with the current version  some errors are thrown:

`2018-03-24 15:26:07 DEBUG    connectionpool Thread-467   http://192.168.178.77:1400 "POST /DeviceProperties/Control HTTP/1.1" 200 296 -- connectionpool.py:_make_request:396
Exception ignored in: <generator object iter_slices at 0x7fecf56abe08>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/utils.py", line 449, in iter_slices
    def iter_slices(string, slice_length):
SystemError: error return without exception set
2018-03-24 15:26:07 DEBUG    connectionpool Thread-467   Starting new HTTP connection (1): 192.168.178.77 -- connectionpool.py:_new_conn:208
Exception ignored in: <generator object HTTPResponse.__init__.<locals>.<genexpr> at 0x7fecf56abe08>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 150, in <genexpr>
    encodings = (enc.strip() for enc in tr_enc.split(","))
SystemError: error return without exception set
2018-03-24 15:26:07 DEBUG    connectionpool Thread-467   http://192.168.178.77:1400 "POST /MediaServer/ContentDirectory/Control HTTP/1.1" 200 None -- connectionpool.py:_make_request:396
Exception ignored in: <generator object iter_slices at 0x7fecf56ab7d8>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/utils.py", line 449, in iter_slices
    def iter_slices(string, slice_length):
SystemError: error return without exception set`

This seems to happen while making HTTp requests.  

Pfischi

**Comment by ghcs27** [comment]
Strange, but no file from the SoCo shows up in the traceback, so we've got no clue where the bug is (or even if it is in our code at all).
It seems like some C code, called by requests and urllib, returns a non-zero exit code.
Specifically, the third party module, interfacing with the Python C API returned an incorrect result, reporting an exception should have been raised, but did not tell Python which exception is that.
