### ISSUE TITLE
Reload list song title

### ISSUE THREAD

**Issue by Psychokiller1888** [SoCo/SoCo#610]
Hello!

Thank you for this wonderful API!

I'm using it in conjuction with Snips which is a voice assistant that runs offline. I'm using my Sonos for it to speak to me

When my Sonos is playing something, I pause the music, record the playlist, record the track number playing, the position in track, delete the list, play the audio file the containingg my assistant's answer and then repush the playlist, set the correct track number and the correct track position. The problem is about the track naming then....

Before anything, the names appear correctly:

https://puu.sh/zRPre.png

But when I reinject the play list they all appear like this:

https://puu.sh/zRPxx.png

How do I do this, well like this:

```
backupQueue = player.get_queue()
player.clear_queue()
......
if len(backupQueue) > 0:
    for track in backupQueue:
        player.add_to_queue(track)
.......
```

This happens with local music or music from google music

Thank you for any advice

**Comment by DPH** [comment]
Hi @Psychokiller1888 
restoring playlist does appear to loose the correct titles - I think this has always been the case.

However to play a voice announcement you don't need to remove the playlist, you can just play the voice file then re-instate playing from the playlist. 
SoCo has a snapshot feature that handles a lot of this for you. 
See the examples https://github.com/SoCo/SoCo/blob/master/examples/snapshot/basic_snap.py and 
https://github.com/SoCo/SoCo/blob/master/examples/snapshot/multi_zone_snap.py

This works well for playlists, radio etc. The only thing it can't do is re-start a cloud queue created from Alexa as the queue is not accessible at present - trying to get Sonos to help with this!

Let us know if this provides a work around for you or if you need more help.

Cheers David

**Comment by Psychokiller1888** [comment]
I tried the snapshot approach at first, and was blocked by I don't remember what. I'm gonna give it a try again just now, so I know what the problem was. I think I couldn't play the sound file from the samba server on my raspberry

**Comment by Psychokiller1888** [comment]
@DHP

Ok, I tried snapshot again, and discovered that I had to use x-file-cifs://ip/file.mp3 to play the file on my raspberry samba server. Playing it while sonos is playing something else goes fine but restoring fails:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2650, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1003, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1284, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1849, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2305, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2500, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2647, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/home/pi/ProjectAlice/mqttServer.py", line 149, in onMessage
    if module.onMessage(self, message.topic, message):
  File "/home/pi/ProjectAlice/modules/Time.py", line 77, in onMessage
    _mqttServer.endTalk(sessionId, coreModule.getRandomTalk(_MODULE_NAME, 'time').format(time), client=siteId)
  File "/home/pi/ProjectAlice/mqttServer.py", line 323, in endTalk
    self.speakOnSonos(text, client)
  File "/home/pi/ProjectAlice/mqttServer.py", line 335, in speakOnSonos
    sonosModule.aliceSpeak(client)
  File "/home/pi/ProjectAlice/modules/Sonos.py", line 278, in aliceSpeak
    snapshot.restore()
  File "/usr/local/lib/python2.7/dist-packages/soco/snapshot.py", line 218, in restore
    self.device.bass = self.bass
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 723, in bass
    bass = int(bass)
TypeError: int() argument must be a string or a number, not 'NoneType'


The queue was created through the sonos app, and is played from Google Music

**Comment by Psychokiller1888** [comment]
Thank you for making me try snapshot again!

**Comment by DPH** [comment]
Hi, does snapshot now work or is restore still failing?
Cheers David

**Comment by Psychokiller1888** [comment]
It works, the error was me not taking the snapshot before trying to restore it... Kept the original message for history

**Comment by DPH** [comment]
Great - have fun with it
Cheers David
