### ISSUE TITLE
Unknown UPnP class: object.item.audioItem.audioBook

### ISSUE THREAD

**Issue by naimo84** [SoCo/SoCo#616]
Hey guys,
I've a problem with SoCo an my new Sonos One.

```
2018-05-16T05:16:37.924830698Z ----------------------------------------
2018-05-16T05:16:37.924839798Z Exception happened during processing of request from ('192.168.11.142', 38766)
2018-05-16T05:16:37.924847803Z Traceback (most recent call last):
2018-05-16T05:16:37.924860457Z   File "/usr/lib/python3.6/site-packages/soco/data_structures_entry.py", line 49, in from_didl_string
2018-05-16T05:16:37.924868577Z     cls = _DIDL_CLASS_TO_CLASS[item_class]
2018-05-16T05:16:37.924875744Z KeyError: 'object.item.audioItem.audioBook'
2018-05-16T05:16:37.924882865Z 
2018-05-16T05:16:37.924889745Z During handling of the above exception, another exception occurred:
2018-05-16T05:16:37.924897083Z 
2018-05-16T05:16:37.924903855Z Traceback (most recent call last):
2018-05-16T05:16:37.924911652Z   File "/usr/lib/python3.6/socketserver.py", line 639, in process_request_thread
2018-05-16T05:16:37.924919408Z     self.finish_request(request, client_address)
2018-05-16T05:16:37.924926679Z   File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
2018-05-16T05:16:37.924934257Z     self.RequestHandlerClass(request, client_address, self)
2018-05-16T05:16:37.924941546Z   File "/usr/lib/python3.6/socketserver.py", line 696, in __init__
2018-05-16T05:16:37.924949040Z     self.handle()
2018-05-16T05:16:37.924956309Z   File "/usr/lib/python3.6/http/server.py", line 418, in handle
2018-05-16T05:16:37.924963761Z     self.handle_one_request()
2018-05-16T05:16:37.924970803Z   File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
2018-05-16T05:16:37.924978440Z     method()
2018-05-16T05:16:37.924985726Z   File "/usr/lib/python3.6/site-packages/soco/events.py", line 239, in do_NOTIFY
2018-05-16T05:16:37.924993395Z     variables = parse_event_xml(content)
2018-05-16T05:16:37.925000595Z   File "/usr/lib/python3.6/site-packages/soco/events.py", line 139, in parse_event_xml
2018-05-16T05:16:37.925008220Z     value = from_didl_string(value)[0]
2018-05-16T05:16:37.925015434Z   File "/usr/lib/python3.6/site-packages/soco/data_structures_entry.py", line 51, in from_didl_string
2018-05-16T05:16:37.925023342Z     raise DIDLMetadataError("Unknown UPnP class: %s" % item_class)
2018-05-16T05:16:37.925030984Z soco.exceptions.DIDLMetadataError: Unknown UPnP class: object.item.audioItem.audioBook
2018-05-16T05:16:37.925038448Z ----------------------------------------
```

All of my other 5 Sonos Player (Play:1 and Play:3) work great with SoCo.
This is my Code. The purpose is to connect Sonos via MQTT to my FHEM Docker Server.

Do you see any hint, what's causing the problem.
Thanks a lot in advance.

Greetz,
Benjamin

```
from __future__ import print_function, unicode_literals
import time
import json
import _thread
import soco
import queue
from pprint import pprint
from soco import discovery
from soco.events import event_listener
from soco.snapshot import Snapshot
import paho.mqtt.client as mqtt

sonosList = list()


class SpeakerEvents():
    def __init__(self, speaker, client):
        self.device = speaker
        self.sub2 = self.device.avTransport.subscribe()  # track_information
        self.sub3 = self.device.renderingControl.subscribe()  # volume_information
        _thread.start_new_thread(
            sonos_trackhandler,  (self.sub2, self.device, client))
        _thread.start_new_thread(sonos_volumehandler,
                                 (self.sub3, self.device, client))


class SonosSpeakerInstance():
    def __init__(self, speaker, client):
        self.speaker = speaker
        self.client = client
        self.EventListener(self.speaker)

    def EventListener(self, speaker):
        self.speaker = speaker
        #print("instance speaker {}".format(self.speaker))
        if self.speaker.is_coordinator == True:
            SpeakerEvents(self.speaker, self.client)
        else:
            pass

    def AllSpeakerInformation(self, speaker):
        self.speaker = speaker
        currently_playing = self.speaker.get_current_track_info()
        self.speaker = speaker
        speaker_info = {"speaker_name": self.speaker.player_name,
                        "ip_address": self.speaker.ip_address,
                        "album": currently_playing["album"],
                        "title": currently_playing["title"],
                        "artist": currently_playing["artist"],
                        "album_art": currently_playing["album_art"]
                        }

        return speaker_info

    def ArtImage(self, speaker_info):
        pass

    def SpeakerSubscriptionAvTransport(self, speaker):
        sub2 = speaker.avTransport.subscribe()
        while True:
            try:
                event = sub2.event.get(timeout=0.5)
                self.TransportState(event.variables.get("transport_state"))

            except:
                pass

    def TransportState(self, speaker_avTransport_info):
        self.speaker_info = speaker_avTransport_info
        # print(self.speaker_info)


def SpeakerVolume(speaker):
    pass


def on_connect(client, userdata, flags, rc):
    pprint(rc)
    client.subscribe("sonos2/set/#")


def on_message(client, userdata, msg):
    words = msg.topic.split("/")

    if words[1] == "set":
        ip = next(
            dev for dev in sonosList if dev.speaker.player_name == words[2])
        device = soco.SoCo(ip.speaker.ip_address)

        if words[3] == "notify":
            notify = json.loads(msg.payload)
            pprint(notify["uri"])
            alert_uri = notify["uri"]
            # 1) create a Snapshot class for this device
            snap = Snapshot(device)
            snap.snapshot()          # 2) take a snapshot of this device's status
            device.volume = notify["volume"]
            # play an alert sound
            device.play_uri(alert_uri, title='my alert')
            time.sleep(10)                                  # wait for a bit !
            snap.restore(fade=True)
        if words[3] == "addMember":
            ip_slave = next(
                dev2 for dev2 in sonosList if dev2.speaker.player_name == msg.payload.decode("utf-8"))
            slave = soco.SoCo(ip_slave.speaker.ip_address)
            slave.join(device)

        if words[3] == "removeMember":
            ip_slave = next(
                dev2 for dev2 in sonosList if dev2.speaker.player_name == msg.payload.decode("utf-8"))
            slave = soco.SoCo(ip_slave.speaker.ip_address)
            slave.unjoin()

        if words[3] == "volume":
            device.volume = msg.payload

        if words[3] == "control":
            pprint(msg.payload)
            if msg.payload.decode("utf-8") == "play":
                device.play()
            if msg.payload.decode("utf-8") == "pause":
                device.pause()


def on_log(client, userdata, level, buf):
    pass  # print("log: ", buf)


def sonos_volumehandler(volume, device, client):
    while True:
        try:
            event = volume.events.get(timeout=1)
            client.publish("sonos2/status/"+device.player_name+"/volume",
                           event.variables["volume"]["Master"], 0, True)
        except queue.Empty:
            pass

        except KeyboardInterrupt:
            volume.unsubscribe()
            event_listener.stop()
            break


def sonos_trackhandler(track, device, client):
    while True:
        try:
            event = track.events.get(timeout=1)
            client.publish("sonos2/status/"+device.player_name+"/transport_state",
                           event.variables["transport_state"], 0, True)
        except queue.Empty:
            pass

        except KeyboardInterrupt:
            track.unsubscribe()
            event_listener.stop()
            break


def main():
    client = mqtt.Client()
    client.on_connect = on_connect
    client.on_message = on_message
    client.on_log = on_log

    for zone in soco.discover():
        sonosList.append(SonosSpeakerInstance(zone, client))

    try:
        client.connect("192.168.11.3", 1883, 60)
        client.loop_forever()
    except:
        pass 

if __name__ == "__main__":
    main()
```

**Comment by ghcs27** [comment]
Thank you for reporting this bug!
It looks like your library contains audio books, but SoCo doesn't know how to deal with audio books yet. It should be possible to create the necessary class - I'll try to make a bug fix soon!

**Comment by ghcs27** [comment]
If you want to, you could do the PR yourself.
