### ISSUE TITLE
occasional snapshot() error with "cross_fade" property

### ISSUE THREAD

**Issue by rudyvan** [SoCo/SoCo#621]
I sometimes have and error when calling snapshot().   On 40 calls a day the error appears less than 2 times.  I am using version 0.14

Maybe the error comes from other things my script does, but the code leading up to the error is really streightforward:

```
zones = list(soco.discover())
for zone in zones:
	resume[zone.ip_address]=SoCoCam(zone)
	if resume[zone.ip_address].snapshot(): # it returns True when the snapshot zone is a coordinator
		coordinators.append(zone); volumes[zone.ip_address]=zone.volume
		try: zone.pause() # can not pause TV, so could throw off an error
		except: pass
		if not zone.is_playing_tv: zone.volume=self.volume
	        else: memberships[zone.ip_address]=zone.group.coordinator
```

error:

```
Traceback (most recent call last):
  File "/home/pi/voice.py", line 123, in sonos_thread
    if resume[zone.ip_address].snapshot(): # it returns True when the snapshot zone is a coordinator
  File "/usr/local/lib/python3.5/dist-packages/soco/snapshot.py", line 130, in snapshot
    self.cross_fade = self.device.cross_fade
  File "/usr/local/lib/python3.5/dist-packages/soco/core.py", line 104, in inner_function
    raise SoCoSlaveException(message)
soco.exceptions.SoCoSlaveException: The method or property "cross_fade" can only be called/used on the coordinator in a group
```

Any reason this could happen?
Thanks in advance for feedback!

**Comment by DPH** [comment]
Hi @rudyvan 
useful to know there are some occasional issues on long running processes. 
Is this the same error we had back in #519?
We did a fix (although not sure it really made a difference - but used SoCo functions) in #529 

Somehow we are identifying a player as coordinator when it is not. Either it is stale information or a logic problem somewhere.

Will try to have a look at this, but am not here much for the next couple of weeks.
Shout if you have any brain waves, or if anyone else has ideas.

Regards Daivd

**Comment by rudyvan** [comment]
Indeed, is the same issue, it did not get away.

Kind Regards,
Rudy

**Comment by ghcs27** [comment]
It seems like device.cross_fade is queried even if the device is not a coordinator, but the getter raises an exception in that case.
