### ISSUE TITLE
Night_mode and dialog_mode not supported on Playbase

### ISSUE THREAD

**Issue by arsaboo** [SoCo/SoCo#633]
I just tried changing the `night_mode` and `dialog_mode` on my Playbase, but get an error for both as not supported. I can change these modes from the Sonos app, so looks like it is a SoCo limitation. 

```
>>> my_zone
SoCo("192.168.2.253")
>>> my_zone.get_speaker_info()
{u'display_version': '9.1', u'player_icon': '/img/icon-S11.png', u'uid': 'RINCON_XYZ', u'software_version': '45.1-56150', u'mac_address': u'MA-CA-DD-RE-S-S', u'hardware_version': '1.14.1.11-1', u'model_number': 'S11', u'serial_number': 'MA-CA-DD-RE-S-S:1', u'zone_name': 'Family Room', u'model_name': 'Sonos Playbase'}
>>> my_zone.night_mode = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 813, in night_mode
    raise NotSupportedException(message)
soco.exceptions.NotSupportedException: This device does not support night mode
>>> my_zone.dialog_mode = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 851, in dialog_mode
    raise NotSupportedException(message)
soco.exceptions.NotSupportedException: This device does not support dialog mode
```

Let me know if you need any other details

**Comment by arsaboo** [comment]
Looks like these lines in the core.py are causing the issues:
`if 'PLAYBAR' not in self.speaker_info['model_name']:`

Firstly, `Playbase` or `Beam` are not listed in core.py. Second, the case for `speaker_info` has changed - instead of all caps that is currently being used, it is `Playbase`. I suspect the `night_mode` and `speech_enhance` are currently broken for everyone (not just Playbase users). Changing those lines to 

`if self.speaker_info['model_name'] not in {'Sonos Playbase', 'Sonos Playbar', 'Sonos Beam'}:`

worked in my case. If this approach is acceptable, I can create a PR.
