### ISSUE TITLE
join player to group results in 501 UPnp error

### ISSUE THREAD

**Issue by marcelser** [SoCo/SoCo#643]
I have a small utility which aims to always put the same players in a group. So it discovers the players. Uses one of the players which is to be in the group to get the group name. Then it loops over the group players and unjoins any player which doesn't belong to the group and then joins any player no longer in the group.

It used to work for months, but since some weeks I'm getting an error when the script tries to join a player to the group it fails with:
`ERROR:soco.services:UPnP Error 501 received: Action Failed from 192.168.10.185
Traceback (most recent call last):
  File "/root/.local/lib64/python3.6/site-packages/soco/services.py", line 498, in send_command
    self.handle_upnp_error(response.text)
  File "/root/.local/lib64/python3.6/site-packages/soco/services.py", line 560, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 501 received: Action Failed from 192.168.10.185
Traceback (most recent call last):
  File "sonos_maintain_group.py", line 85, in <module>
    named_players[remaining_player_name].join(lavatory_big)
  File "/root/.local/lib64/python3.6/site-packages/soco/core.py", line 1045, in join
    ('CurrentURIMetaData', '')
  File "/root/.local/lib64/python3.6/site-packages/soco/services.py", line 213, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/root/.local/lib64/python3.6/site-packages/soco/services.py", line 498, in send_command
    self.handle_upnp_error(response.text)
  File "/root/.local/lib64/python3.6/site-packages/soco/services.py", line 560, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 501 received: Action Failed from 192.168.10.185
`
I'm using Soco 0.16 and have no clue how to solve this.

Maybe as an additional information I made a pprint on the group and this looks like this:;
`ZoneGroup(uid='RINCON_000E5871B45A01400:146', coordinator=SoCo("192.168.10.159"), members={SoCo("192.168.10.159"), SoCo("192.168.10.176")})`

**Comment by marcelser** [comment]
actually shortly after posting this issue. I found out that soco no longer supports just adding a speaker to another speaker in the group which is not the coordinator. So I changed to join the speakers to the coordinator and voila it worked. So actually my issue is solved.
