### ISSUE TITLE
Challenges working with MusicService

### ISSUE THREAD

**Issue by NickBorgers** [SoCo/SoCo#672]
I am struggling to work with MusicService.
I am referencing this as an example:
https://gist.github.com/lawrenceakka/2d21dca590b4fa7e3af2

On python CLI I am doing:
```
Python 2.7.5 (default, Jun 20 2019, 20:27:34)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import unicode_literals
>>>
>>> from soco import SoCo
>>> from soco.data_structures import DidlItem, DidlResource
>>> from soco.music_services import MusicService
>>> from soco.compat import quote_url
>>>
>>>
>>> device = SoCo("10.10.1.21")  # <------- Your IP here
>>> service = MusicService("Pandora")  # <------ Your Music Service here
/usr/lib/python2.7/site-packages/soco/services.py:686: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  value_list_elt = state.find('{}allowedValueList'.format(ns))\
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/soco/music_services/music_service.py", line 354, in __init__
    "No account found for service: '%s'" % service_name)
soco.exceptions.MusicServiceException: No account found for service: 'Pandora'
>>> service = MusicService("Audible")  # <------ Your Music Service here
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/soco/music_services/music_service.py", line 354, in __init__
    "No account found for service: '%s'" % service_name)
soco.exceptions.MusicServiceException: No account found for service: 'Audible'
```

I seem to be getting the same error message as this which had been repaired:
I have some weird error. It seems not to find my services :  

```
>>> my_zone = SoCo('192.168.1.65')
>>> print(MusicService.get_all_music_services_names())
['SOUNDMACHINE', 'Daytrotter', 'Mixcloud', 'Mood Mix', 'Google Play Music', 'Calm Radio', 'Apple Music', 'SoundCloud', 'Saavn', 'Qobuz', 'Tribe of Noise', 'focus@will', 'TIDAL', 'Gaana', 'FIT Radio Workout Music', 'Napster (BETA)', 'Tunify for Business', 'Concert Vault', 'MLB.com Gameday Audio', 'Spreaker', 'DAR.fm Record Radio', 'Hype Machine', 'Stitcher SmartRadio', 'radioPup', 'Anghami', 'iHeartRadio', 'Murfie', '22tracks', 'TuneIn', 'Bandcamp', 'Radionomy', 'Spotify', 'Deezer', 'Groove', 'Hearts of Space', 'RUSC', 'hotelradio.fm', '7digital']
>>> print(MusicService.get_subscribed_services_names())
[]
>>> print(MusicService.get_subscribed_services_names())
[]
>>> play = MusicService('Google Play Music')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/martinus/Bureau/SoCo-master/soco/music_services/music_service.py", line 351, in __init__
    "No account found for service: '%s'" % service_name)
soco.exceptions.MusicServiceException: No account found for service: 'Google Play Music'
>>>
```

_Originally posted by @Dark5ide in https://github.com/SoCo/SoCo/issues/398#issuecomment-222837535_

**Comment by NickBorgers** [comment]
I think I found an (unfortunate) answer:
https://github.com/SoCo/SoCo/issues/641#issuecomment-427309933

**Comment by NickBorgers** [comment]
I have adopted IFTT (bleh) for controlling my Sonos speakers.
