### ISSUE TITLE
DIDL error for object.item.audioItem.linein.sonos-favorite

### ISSUE THREAD

**Issue by tagdara** [SoCo/SoCo#729]
I know I submit a lot of these, but with the next version coming up I wanted to make sure this one is in line with the proposed fixes.  I think it is a compound problem from previous issues where there is no linein object AND there's no linein.sonos-favorite either.

I'm not sure why this freshly happened for me this morning unless its some weird S1/S2 stuff or I recently tagged the line-in as a favorite.   I think it's also possible that when the Sonos auto-switches to the line-in it uses object.item.audioItem.linein and when you manually select it from My Sonos it uses object.item.audioItem.linein.sonos-favorite.  What's even better is that another of my players is somehow listening to the same line-in as a separate ZoneAudio group and has it as object.item.audioItem.linein which also currently breaks.

Data hygiene is totally foreign to Sonos engineers apparently, but needless to say that if we simply rolled up to the closest parent (object.item.audioItem) there would be no negative affect and these would all go away.

In the meantime I'll pile it on the monkey patches on 0.19 until we get to 20.  Every time one of these tiny data errors happen, it silently kills all of the subscriptions which chain-reacts breaking other automations related to music playback in my system.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/soco/data_structures_entry.py", line 49, in from_didl_string
    cls = _DIDL_CLASS_TO_CLASS[item_class]
KeyError: 'object.item.audioItem.linein.sonos-favorite'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/soco/events_base.py", line 107, in parse_event_xml
    value = from_didl_string(value)[0]
  File "/usr/local/lib/python3.7/dist-packages/soco/data_structures_entry.py", line 51, in from_didl_string
    raise DIDLMetadataError("Unknown UPnP class: %s" % item_class)
soco.exceptions.DIDLMetadataError: Unknown UPnP class: object.item.audioItem.linein.sonos-favorite
```

**Comment by tagdara** [comment]
As a follow-up, I did some investigation into what the device was returning for AVTransport and got this interesting tidbit:

(Note that it is actually playing from the line-in on a Sonos connect and I have no Airplay support on any of my Sonos devices)

```
av_transport_uri_meta_data: {
parent_id: "",
item_id: "RINCON_B[redacted]",
restricted: true,
title: "AirPlay Device: Living Room",
desc: ""
},
```

**Comment by KennethNielsen** [comment]
@tagdara 

> Data hygiene is totally foreign to Sonos engineers apparently, but needless to say that if we simply rolled up to the closest parent (object.item.audioItem) there would be no negative affect and these would all go away.

:rofl: WRT data hygiene. The fix with rolling up to the nearest parent should now be released with 0.20. Can you check if it solves the problem?
