### ISSUE TITLE
 ERROR    plugins.sonos.soco.events Exception received in Subscription.renew for Subscription to

### ISSUE THREAD

**Issue by manu241** [SoCo/SoCo#736]
Hallo,

ich bekomme folgende Meldungen in meinem Log.
Was könnte das sein? Die Player sind alle auf dem neusten Stand,

`2020-07-18  02:44:11 ERROR    plugins.sonos.soco.events Exception received in Subscription.renew for Subscription to:
http://192.168.2.159:1400/MediaRenderer/AVTransport/Event, sid: uuid:RINCON_5CAAFD1A657501400_sub0000203428
Traceback (most recent call last):
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 426, in _wrap
    method(*args, **kwargs)
  File "/usr/local/smarthome/plugins/sonos/soco/events_base.py", line 552, in renew
    success,
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 392, in _request
    response.raise_for_status()
  File "/home/smarthome/.local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: http://192.168.2.159:1400/MediaRenderer/AVTransport/Event
2020-07-18  06:53:13 ERROR    plugins.sonos.soco.events Exception received in Subscription.renew for Subscription to:
http://192.168.2.159:1400/MediaRenderer/AVTransport/Event, sid: uuid:RINCON_5CAAFD1A657501400_sub0000204011
Traceback (most recent call last):
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 426, in _wrap
    method(*args, **kwargs)
  File "/usr/local/smarthome/plugins/sonos/soco/events_base.py", line 552, in renew
    success,
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 392, in _request
    response.raise_for_status()
  File "/home/smarthome/.local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: http://192.168.2.159:1400/MediaRenderer/AVTransport/Event
2020-07-18  09:20:13 ERROR    plugins.sonos.soco.events Exception received in Subscription.renew for Subscription to:
http://192.168.2.29:1400/MediaRenderer/AVTransport/Event, sid: uuid:RINCON_000E58F6DF8201400_sub0000204255
Traceback (most recent call last):
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 426, in _wrap
    method(*args, **kwargs)
  File "/usr/local/smarthome/plugins/sonos/soco/events_base.py", line 552, in renew
    success,
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 392, in _request
    response.raise_for_status()
  File "/home/smarthome/.local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: http://192.168.2.29:1400/MediaRenderer/AVTransport/Event
2020-07-18  10:29:13 ERROR    plugins.sonos.soco.events Exception received in Subscription.renew for Subscription to:
http://192.168.2.29:1400/MediaRenderer/AVTransport/Event, sid: uuid:RINCON_000E58F6DF8201400_sub0000204417
Traceback (most recent call last):
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 426, in _wrap
    method(*args, **kwargs)
  File "/usr/local/smarthome/plugins/sonos/soco/events_base.py", line 552, in renew
    success,
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 392, in _request
    response.raise_for_status()
  File "/home/smarthome/.local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: http://192.168.2.29:1400/MediaRenderer/AVTransport/Event
2020-07-18  13:41:21 ERROR    plugins.sonos.soco.events Exception received in Subscription.renew for Subscription to:
http://192.168.2.29:1400/MediaRenderer/AVTransport/Event, sid: uuid:RINCON_000E58F6DF8201400_sub0000204869
Traceback (most recent call last):
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 426, in _wrap
    method(*args, **kwargs)
  File "/usr/local/smarthome/plugins/sonos/soco/events_base.py", line 552, in renew
    success,
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 392, in _request
    response.raise_for_status()
  File "/home/smarthome/.local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: http://192.168.2.29:1400/MediaRenderer/AVTransport/Event
2020-07-18  13:59:23 ERROR    plugins.sonos.soco.events Exception received in Subscription.renew for Subscription to:
http://192.168.2.159:1400/MediaRenderer/AVTransport/Event, sid: uuid:RINCON_5CAAFD1A657501400_sub0000205015
Traceback (most recent call last):
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 426, in _wrap
    method(*args, **kwargs)
  File "/usr/local/smarthome/plugins/sonos/soco/events_base.py", line 552, in renew
    success,
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 392, in _request
    response.raise_for_status()
  File "/home/smarthome/.local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: http://192.168.2.159:1400/MediaRenderer/AVTransport/Event
2020-07-18  16:14:22 ERROR    plugins.sonos.soco.events Exception received in Subscription.renew for Subscription to:
http://192.168.2.156:1400/MediaRenderer/AVTransport/Event, sid: uuid:RINCON_5CAAFD4F229401400_sub0000204921
Traceback (most recent call last):
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 426, in _wrap
    method(*args, **kwargs)
  File "/usr/local/smarthome/plugins/sonos/soco/events_base.py", line 552, in renew
    success,
  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 392, in _request
    response.raise_for_status()
  File "/home/smarthome/.local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: http://192.168.2.156:1400/MediaRenderer/AVTransport/Event`

**Comment by Barry4679** [comment]
I don't speak German, sorry.

I have just received this error also.
SoCo has failed in its attempt to auto renew your Sonos event subscriptions.
In my case something must have happened in my LAN or my Sonos zones. My Sonos zones had reset themselves to the top of the music queues during the night. And I got the same auto-renewal failure log messages.

Your program will need to detect this situation, and resubscribe to the failing zones again.
See here: http://docs.python-soco.com/en/latest/advanced/events.html#autorenew-failure

**Comment by pwt** [comment]
If Sonos devices are rebooted (for example as part of a firmware update), they do not preserve their event subscriptions.
