### ISSUE TITLE
trouble using add_uri_to_queue()

### ISSUE THREAD

**Issue by tgraf2** [SoCo/SoCo#779]
I am having trouble using add_uri_to_queue().  When I use a string directly it works fine,
as shown below:

$ python3
>>> from soco.discovery import by_name
>>> speaker = by_name("Living Room")
>>> line='x-file-cifs://192.168.1.107/share/Alison%20Krauss/Cold%20Mountain-OST/The%20Scarlet%20Tide.mp3'
>>> speaker.add_uri_to_queue(uri=line)
5

When I reference the identical uri from a file, it doesn't work, as shown:

>>> from soco.discovery import by_name
>>> speaker = by_name("Living Room")
>>> with open("playlists/alison_krauss.py", "r+") as f:
...    contents = [x.strip() for x in f.readlines()]
... 
>>> print (contents[0])
>>> line=contents[0]
'x-file-cifs://192.168.1.107/share/Alison%20Krauss/Cold%20Mountain-OST/The%20Scarlet%20Tide.mp3'
speaker.add_uri_to_queue(uri=line)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.6/site-packages/soco/core.py", line 105, in inner_function
    return function(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.6/site-packages/soco/core.py", line 1482, in add_uri_to_queue
    return self.add_to_queue(item, position, as_next)
  File "/home/pi/.local/lib/python3.6/site-packages/soco/core.py", line 105, in inner_function
    return function(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.6/site-packages/soco/core.py", line 1505, in add_to_queue
    ('EnqueueAsNext', int(as_next))
  File "/home/pi/.local/lib/python3.6/site-packages/soco/services.py", line 217, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/home/pi/.local/lib/python3.6/site-packages/soco/services.py", line 501, in send_command
    self.handle_upnp_error(response.text)
  File "/home/pi/.local/lib/python3.6/site-packages/soco/services.py", line 560, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 804 received:  from 192.168.1.102

Any suggestions?

**Comment by pwt** [comment]
What version of SoCo are you using?

Could you try with INFO logging enabled, so we can see exactly what's being sent to the player:

```
import logging
log_format = "%(asctime)s %(filename)s:%(lineno)s - %(funcName)s() - %(message)s"
logging.basicConfig(format=log_format, level=logging.INFO)
```

Thanks.

**Comment by tgraf2** [comment]
Thanks for your reply and the info about logging.  Here's the output, first with the uri as a string:

>>> from soco.discovery import by_name
>>> import logging
>>> log_format = "%(asctime)s %(filename)s:%(lineno)s - %(funcName)s() - %(message)s"
>>> logging.basicConfig(format=log_format, level=logging.INFO)
>>> speaker = by_name("Living Room")
2020-12-19 09:06:58,702 discovery.py:126 - discover() - Sending discovery packets on [<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=17, laddr=('0.0.0.0', 0)>, <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=17, laddr=('0.0.0.0', 0)>]
2020-12-19 09:06:58,833 services.py:475 - send_command() - Sending GetZoneGroupState [] to 192.168.1.106
2020-12-19 09:06:58,904 services.py:486 - send_command() - Received status 200 from 192.168.1.106
>>> line='x-file-cifs://192.168.1.107/share/Alison%20Krauss/Cold%20Mountain-OST/The%20Scarlet%20Tide.mp3'
>>> speaker.add_uri_to_queue(uri=line)
2020-12-19 09:07:30,153 services.py:475 - send_command() - Sending GetZoneGroupState [] to 192.168.1.102
2020-12-19 09:07:30,202 services.py:486 - send_command() - Received status 200 from 192.168.1.102
2020-12-19 09:07:30,206 services.py:475 - send_command() - Sending AddURIToQueue [('InstanceID', 0), ('EnqueuedURI', 'x-file-cifs://192.168.1.107/share/Alison%20Krauss/Cold%20Mountain-OST/The%20Scarlet%20Tide.mp3'), ('EnqueuedURIMetaData', '<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/"><item id="" parentID="" restricted="true"><dc:title /><res protocolInfo="x-rincon-playlist:*:*:*">x-file-cifs://192.168.1.107/share/Alison%20Krauss/Cold%20Mountain-OST/The%20Scarlet%20Tide.mp3</res><upnp:class>object</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">RINCON_AssociatedZPUDN</desc></item></DIDL-Lite>'), ('DesiredFirstTrackNumberEnqueued', 0), ('EnqueueAsNext', 0)] to 192.168.1.102
2020-12-19 09:07:30,241 services.py:486 - send_command() - Received status 200 from 192.168.1.102
39

Now, the uri read from a file:

>>> with open("playlists/alison_krauss.py", "r+") as f:
...    contents = [x.strip() for x in f.readlines()]
... 
>>> print (contents[0])
'x-file-cifs://192.168.1.107/share/wd_red/graf/Music/iTunes/Alison%20Krauss/Cold%20Mountain-OST/The%20Scarlet%20Tide.mp3'
>>> line=contents[0]
>>> speaker.add_uri_to_queue(uri=line)
2020-12-19 09:09:19,988 services.py:475 - send_command() - Sending GetZoneGroupState [] to 192.168.1.102
2020-12-19 09:09:20,043 services.py:486 - send_command() - Received status 200 from 192.168.1.102
2020-12-19 09:09:20,047 services.py:475 - send_command() - Sending AddURIToQueue [('InstanceID', 0), ('EnqueuedURI', "'x-file-cifs://192.168.1.107/share/wd_red/graf/Music/iTunes/Alison%20Krauss/Cold%20Mountain-OST/The%20Scarlet%20Tide.mp3'"), ('EnqueuedURIMetaData', '<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/"><item id="" parentID="" restricted="true"><dc:title /><res protocolInfo="x-rincon-playlist:*:*:*">\'x-file-cifs://192.168.1.107/share/wd_red/graf/Music/iTunes/Alison%20Krauss/Cold%20Mountain-OST/The%20Scarlet%20Tide.mp3\'</res><upnp:class>object</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">RINCON_AssociatedZPUDN</desc></item></DIDL-Lite>'), ('DesiredFirstTrackNumberEnqueued', 0), ('EnqueueAsNext', 0)] to 192.168.1.102
2020-12-19 09:09:20,133 services.py:486 - send_command() - Received status 500 from 192.168.1.102
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.6/site-packages/soco/core.py", line 105, in inner_function
    return function(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.6/site-packages/soco/core.py", line 1482, in add_uri_to_queue
    return self.add_to_queue(item, position, as_next)
  File "/home/pi/.local/lib/python3.6/site-packages/soco/core.py", line 105, in inner_function
    return function(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.6/site-packages/soco/core.py", line 1505, in add_to_queue
    ('EnqueueAsNext', int(as_next))
  File "/home/pi/.local/lib/python3.6/site-packages/soco/services.py", line 217, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/home/pi/.local/lib/python3.6/site-packages/soco/services.py", line 501, in send_command
    self.handle_upnp_error(response.text)
  File "/home/pi/.local/lib/python3.6/site-packages/soco/services.py", line 560, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 804 received:  from 192.168.1.102

I can see that the uri has double quotes, which is probably the problem.  I imagine that I can fix the problem by removing the quotes from the uris in the file (haven't tried that yet).  I don't know the version of soco that I am using (not sure how to check that).  Thanks again.

**Comment by tgraf2** [comment]
Update: I removed the quotes from the uris in the file and it now works.  Before I close the issue, I would like to suggest that the documentation could be improved.  Here are a few suggestions:  (1) add_uri_to_queue should mention how to reference uris from a file (and that quotes should not be included), (2) information on how to turn on logging and format the output should be prominent, (3) when you see 'UPnP Error 804', here are a few things to try...  Thanks again

**Comment by pwt** [comment]
> I can see that the uri has double quotes, which is probably the problem. I imagine that I can fix the problem by removing the quotes from the uris in the file (haven't tried that yet).

Yes, it's the quotes within quotes that's the issue -- i.e., the inner single quotes become part of the string being sent to the player.

You could remove them by modifying your code to use `x.strip("'")` or `x.strip().replace("'", "")` depending on what's in the file being read.

>  I don't know the version of soco that I am using (not sure how to check that).

For future reference, it's in: `soco.__version__` (or use `pip freeze`).

Looks like we've resolved this issue, so I'll close it.

**Comment by pwt** [comment]
>I would like to suggest that the documentation could be improved. Here are a few suggestions: (1) add_uri_to_queue should mention how to reference uris from a file (and that quotes should not be included)

I'm going to politely disagree on this one. Your original code was sending a malformed URL string.

> (2) information on how to turn on logging and format the output should be prominent

Possibly, though this is standard Python know-how. SoCo just uses standard Python logging.

> (3) when you see 'UPnP Error 804', here are a few things to try...

Some documented troubleshooting recipes would undoubtedly be useful, but it would take someone to volunteer to write them :)
