### ISSUE TITLE
No TTS during TV mode

### ISSUE THREAD

**Issue by sracing** [SoCo/SoCo#805]
I am using the Sonos Plugin on SmarthomeNG, which is using SoCo. While TTS works flawless on any device during streaming mode, it seems that some user of this plugin reported missing TTS support at least for typical surround devices (e.g. a set of Playbar, Sub and 2x Play1) just during TV mode. WHen trying do do TTS output during TV mode, the error message is:

`2021-02-09 14:49:48 ERROR lib.item Item sonos.wohnzimmer.play_tts: problem running <bound method Sonos.update_item of <plugins.sonos.Sonos object at 0x7fcbd86dc320>>: UPnP Error 701 received: Transition not available from 192.168.178.47
> Traceback (most recent call last):
> File "/usr/local/smarthome/lib/item.py", line 2368, in __update
> method(self, caller, source, dest)
> File "/usr/local/smarthome/plugins/sonos/__init__.py", line 2698, in update_item
> volume, self._snippet_duration_offset, fade_in)
> File "/usr/local/smarthome/plugins/sonos/__init__.py", line 2278, in play_tts
> self._play_snippet(file_path, webservice_url, volume, duration_offset, fade_in)
> File "/usr/local/smarthome/plugins/sonos/__init__.py", line 2206, in _play_snippet
> self.set_stop()
> File "/usr/local/smarthome/plugins/sonos/__init__.py", line 1434, in set_stop
> if not sonos_speaker[self.coordinator].soco.stop():
> File "/usr/local/smarthome/plugins/sonos/soco/core.py", line 121, in inner_function
> return function(self, *args, **kwargs)
> File "/usr/local/smarthome/plugins/sonos/soco/core.py", line 658, in stop
> self.avTransport.Stop([("InstanceID", 0), ("Speed", 1)])
> File "/usr/local/smarthome/plugins/sonos/soco/services.py", line 217, in _dispatcher
> return self.send_command(action, *args, **kwargs)
> File "/usr/local/smarthome/plugins/sonos/soco/services.py", line 507, in send_command
> self.handle_upnp_error(response.text)
> File "/usr/local/smarthome/plugins/sonos/soco/services.py", line 566, in handle_upnp_error
> error_xml=xml_error,
> plugins.sonos.soco.exceptions.SoCoUPnPException: UPnP Error 701 received: Transition not available from 192.168.178.47`

The author of the SmarthomeNG Sonos Plugin declared that the underlying root cause is on SoCo.

Regards
Marcus

**Comment by pwt** [comment]
The error `UPnP Error 701 received: Transition not available from 192.168.178.47` means that the speaker has been asked to do something it doesn't support in its current state (for example, instructing a speaker to move to the next track when it's playing from its Line In input).

In this case, it looks like the speaker is rejecting a `stop()` instruction when playing a TV source.  I don't think it's a SoCo bug, per se.

I don't have any Sonos AV setups available to test, but it would be useful to know what commands the speaker will accept when playing a TV source. You can do this using:

`<SoCo-Object>.avTransport.GetCurrentTransportActions([('InstanceID', 0)])`

**Comment by rytilahti** [comment]
Here's the output from a beam:
```
>>> dev.avTransport.GetCurrentTransportActions([('InstanceID', 0)])
{'Actions': 'Set, Play'}
```

**Comment by pwt** [comment]
> Here's the output from a beam:
> 
> ```
> >>> dev.avTransport.GetCurrentTransportActions([('InstanceID', 0)])
> {'Actions': 'Set, Play'}
> ```

Thanks. Just to confirm: is that while the Beam is playing from its TV input?

**Comment by rytilahti** [comment]
Yes, that's when playing from the TV input. Here's the list of actions when playing music (from spotify this time), for completeness:
```
>>> dev.avTransport.GetCurrentTransportActions([('InstanceID', 0)])
{'Actions': 'Set, Stop, Pause, Play, X_DLNA_SeekTime, Next, Previous'}
```

**Comment by DPH** [comment]
I have the same problem - looking at options to solve.
Not sure if it's linked to #584 or #761
