### ISSUE TITLE
discover() fails when sonos device gets unplugged

### ISSUE THREAD

**Issue by ItsEcholot** [SoCo/SoCo#828]
Discover fails with the following traceback when a previously discovered sonos device gets unplugged:

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.7/http/client.py", line 1260, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1306, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1255, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1030, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 970, in send
    self.connect()
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xb18b4070>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.178.120', port=1400): Max retries exceeded with url: /xml/ZoneGroupTopology1.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb18b4070>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "src/__main__.py", line 63, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "src/__main__.py", line 39, in main
    networking.initial_check(),
  File "src/balancing/manager.py", line 30, in start_discovery
    await self.sonos.discover_loop()
  File "src/balancing/sonos.py", line 25, in discover_loop
    speakers = self.sonos_adapter.discover()
  File "src/sonos/adapter_soco.py", line 29, in discover
    name = speaker.player_name
  File "/home/pi/.local/lib/python3.7/site-packages/soco/core.py", line 321, in player_name
    self._parse_zone_group_state()
  File "/home/pi/.local/lib/python3.7/site-packages/soco/core.py", line 1194, in _parse_zone_group_state
    zgs = self.zoneGroupTopology.GetZoneGroupState(cache=self._zgs_cache)[
  File "/home/pi/.local/lib/python3.7/site-packages/soco/services.py", line 207, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/soco/services.py", line 467, in send_command
    args = self.compose_args(action, kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/soco/services.py", line 334, in compose_args
    for action in self.actions:
  File "/home/pi/.local/lib/python3.7/site-packages/soco/services.py", line 664, in actions
    self._actions = list(self.iter_actions())
  File "/home/pi/.local/lib/python3.7/site-packages/soco/services.py", line 691, in iter_actions
    scpd_body = requests.get(self.base_url + self.scpd_url, timeout=10).content
  File "/home/pi/.local/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.178.120', port=1400): Max retries exceeded with url: /xml/ZoneGroupTopology1.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb18b4070>: Failed to establish a new connection: [Errno 113] No route to host'))
```

It might have something to do with the following comment I found in the source:
```
                    # Now we have an IP, we can build a SoCo instance and query
                    # that player for the topology to find the other players.
                    # It is much more efficient to rely upon the Zone
                    # Player's ability to find the others, than to wait for
                    # query responses from them ourselves.
```

Is it possible that soco fails with the discovery because it trusts the other Sonos device (which is still plugged in) and which provides outdated topology data?

**Comment by pwt** [comment]
> Is it possible that soco fails with the discovery because it trusts the other Sonos device (which is still plugged in) and which provides outdated topology data?

Probably correct. It takes a Sonos system some time to stabilise when a player is switched off, since it's not really designed to have players coming and going.

I'll take a look at catching the exception in the discovery code and proceeding.

(I was going to suggest using `scan_network()` as a fallback discovery mechanism, but I suspect it's vulnerable to the same limitation.)

**Comment by pwt** [comment]
Just to note that I did some testing with a Sonos Move, flipping it to bluetooth mode and immediately calling `discover()`. This does not provoke the exception; perhaps the Move signs off the Sonos network before it switches to BT.

**Comment by pwt** [comment]
Hi @ItsEcholot: Looking at the stack trace more closely, the exception is raised not in SoCo `discover()`, but in the lookup of the `player_name` property in your code:

```
File "src/balancing/manager.py", line 30, in start_discovery
    await self.sonos.discover_loop()
  File "src/balancing/sonos.py", line 25, in discover_loop
    speakers = self.sonos_adapter.discover()

  *** File "src/sonos/adapter_soco.py", line 29, in discover
  ***     name = speaker.player_name

  File "/home/pi/.local/lib/python3.7/site-packages/soco/core.py", line 321, in player_name
    self._parse_zone_group_state()
```

SoCo's `discover()` function is correctly returning the speakers the Sonos system thinks are present, which includes the speaker that's been turned off as far as Sonos is concerned. I don't think there's much that SoCo can do about this.

In `adapter_soco.py` (after line 28), you could insert a try/catch to omit from your list any speakers that don't respond?

**Comment by ItsEcholot** [comment]
> Hi @ItsEcholot: Looking at the stack trace more closely, the exception is raised not in SoCo `discover()`, but in the lookup of the `player_name` property in your code:

You're absolutely right about this, I missed this while investigating it.

> SoCo's `discover()` function is correctly returning the speakers the Sonos system thinks are present, which includes the speaker that's been turned off as far as Sonos is concerned. I don't think there's much that SoCo can do about this.

I now understand the technological reasoning behind this but I just think this isn't what most users (including me) are expecting. When I receive a SoCo instance from the discovery process I of course assume that this instance has already been successfully contacted (how else would it have been discovered? I now know how but do others?).
The Sonos App also doesn't list unavailable speakers and it seems that opening the app actually forces the Sonos System to update it's internal topology cache... Not 100% sure on this one though, would have to investigate this further.
So either the documentation should have a prominent note about this or we could check if the instance can actually be contacted before returning it in discovery. If this carries too much of a performance penalty we could add a discovery parameter that when set to true only returns "confirmed" instances. What is your opinion on this?

> In `adapter_soco.py` (after line 28), you could insert a try/catch to omit from your list any speakers that don't respond?

Yep that will work, thanks 👍

**Comment by pwt** [comment]
> I now understand the technological reasoning behind this but I just think this isn't what most users (including me) are expecting. When I receive a SoCo instance from the discovery process I of course assume that this instance has already been successfully contacted (how else would it have been discovered? I now know how but do others?).

Yes, you're probably right about this.

> The Sonos App also doesn't list unavailable speakers and it seems that opening the app actually forces the Sonos System to update it's internal topology cache... Not 100% sure on this one though, would have to investigate this further.

Same here ... not sure about that, but it's plausible.

> So either the documentation should have a prominent note about this or we could check if the instance can actually be contacted before returning it in discovery. If this carries too much of a performance penalty we could add a discovery parameter that when set to true only returns "confirmed" instances. What is your opinion on this?

Adding a note to the documentation seems prudent. I'll take a look at that.

The problem with checking for contact-ability at the point of discovery is that a speaker may only be offline briefly (e.g., off the network temporarily, or being rebooted). Conversely, a speaker's connectivity state can change at any time, so checking it at the point of discovery doesn't guarantee it will be accessible at a later time.

We could add a simple presence-checker function that takes a set of SoCo objects and returns only the ones that are contactable at that point in time. This could be called at any time, including immediately after discovery.

**Comment by ItsEcholot** [comment]
> The problem with checking for contact-ability at the point of discovery is that a speaker may only be offline briefly (e.g., off the network temporarily, or being rebooted). Conversely, a speaker's connectivity state can change at any time, so checking it at the point of discovery doesn't guarantee it will be accessible at a later time.
> 
> We could add a simple presence-checker function that takes a set of SoCo objects and returns only the ones that are contactable at that point in time. This could be called at any time, including immediately after discovery.

I think you're right this would probably be the best solution all things considered. This way the people using the library could decide on their own how often and when they want to check if their instances are contactable 👍

**Comment by pwt** [comment]
> I think you're right this would probably be the best solution all things considered. This way the people using the library could decide on their own how often and when they want to check if their instances are contactable 👍

Sounds good. I should also note that there's probably a way of subscribing to topology change events, but it's not something I've tried.

Docs note is at: https://github.com/SoCo/SoCo/commit/5f4d872e5b4d89796cadec33dd4cd18ef1457641

**Comment by pwt** [comment]
@ItsEcholot If you have time to review it, the new `contactable()` function PR is #834.
