### ISSUE TITLE
Unable to authenticate to Tidal music service

### ISSUE THREAD

**Issue by goldyfruit** [SoCo/SoCo#891]
I'm trying to use Tidal with Sonos, my Tidal and Sonos accounts are both linked.

```
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> tidal = MusicService("TIDAL")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'MusicService' is not defined
>>> from soco.music_services.music_service import MusicService
>>> tidal = MusicService("TIDAL")
>>> url = tidal.begin_authentication()
Traceback (most recent call last):
  File "/home/goldyfruit/Virtualenvs/soco/lib/python3.9/site-packages/soco/music_services/music_service.py", line 197, in call
    result_elt = message.call()
  File "/home/goldyfruit/Virtualenvs/soco/lib/python3.9/site-packages/soco/soap.py", line 324, in call
    raise SoapFault(faultcode, faultstring, faultdetail)
soco.soap.SoapFault: Client.AuthTokenExpired: Client.AuthTokenExpired

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/goldyfruit/Virtualenvs/soco/lib/python3.9/site-packages/soco/music_services/music_service.py", line 787, in begin_authentication
    ) = self.soap_client.begin_authentication()
  File "/home/goldyfruit/Virtualenvs/soco/lib/python3.9/site-packages/soco/music_services/music_service.py", line 297, in begin_authentication
    result = self.call(
  File "/home/goldyfruit/Virtualenvs/soco/lib/python3.9/site-packages/soco/music_services/music_service.py", line 200, in call
    raise MusicServiceAuthException(
soco.exceptions.MusicServiceAuthException: Authorization for TIDAL expired, is invalid or has not yet been completed: [Client.AuthTokenExpired / Client.AuthTokenExpired / None]
>>> 
```

When I try via Postman to retrieve the DeviceLink I got this:
```xml
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
    <soap-env:Body>
        <soap-env:Fault>
            <faultcode>Client.AuthTokenExpired</faultcode>
            <faultstring>Client.AuthTokenExpired</faultstring>
        </soap-env:Fault>
    </soap-env:Body>
</soap-env:Envelope>
```

**Comment by goldyfruit** [comment]
I tried with two different accounts just in case, same issue.

**Comment by goldyfruit** [comment]
Maybe in the payload sent to Tidal, a token or a key is/are required.

```xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:s="http://www.sonos.com/Services/1.1">
  <soap:Header>
    <s:context>
      <s:timezone>+01:00</s:timezone>
    </s:context>
    <s:credentials>
      <s:deviceId>XXXX</s:deviceId>
      <s:loginToken>
        <s:token></s:token>      <-------- HERE
        <s:key></s:key>            <-------- HERE
        <s:householdId>XXXXX</s:householdId>
      </s:loginToken>
    </s:credentials>
  </soap:Header>
  <soap:Body>
    <s:getDeviceLinkCode>
      <s:householdId>XXXXX</s:householdId>
    </s:getDeviceLinkCode>
  </soap:Body>
</soap:Envelope>
```

**Comment by goldyfruit** [comment]
#892
