### ISSUE TITLE
SoCo raising exception on speaker unsubscribe

### ISSUE THREAD

**Issue by aschwith** [SoCo/SoCo#931]
With SoCo version 28.0.1. and before, the following exception occurs when trying to unsubscripe a SoCo event for a speaker under certain circumstances. My guess is that this exception occurs if the speaker is offline in that moment:

Traceback (most recent call last):

		  File "/usr/local/smarthome/plugins/sonos/__init__.py", line 212, in unsubscribe
		    self._event.unsubscribe()
		  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 342, in unsubscribe
		    return self._wrap(unsubscribe, strict)
		  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 442, in _wrap
		    method(*args, **kwargs)
		  File "/usr/local/smarthome/plugins/sonos/soco/events_base.py", line 568, in unsubscribe
		    return self._request(
		  File "/usr/local/smarthome/plugins/sonos/soco/events.py", line 407, in _request
		    success(response.headers)
		AttributeError: 'NoneType' object has no attribute 'headers'

**Comment by pwt** [comment]
Thanks for the defect report. The referenced PR should prevent the exception.

**Comment by aschwith** [comment]
Thanks for the fast fix.
