### ISSUE TITLE
ConnectionResetError(54, 'Connection reset by peer') when ping works completely fine

### ISSUE THREAD

**Issue by rgodha24** [SoCo/SoCo#966]
Hi,

I'm trying to connect to a sonos speaker (obviously lol) using the soco library. 

I'm trying to run this, and I get an error requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
```python
from soco import SoCo

speaker = SoCo("<local_ip>")
print(speaker.player_name)
```

running ping <local_ip> works completely fine 

here's the complete stacktrace: 
<details><summary>Stacktrace</summary>
<p>
Traceback (most recent call last):
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/.local/share/uv/python/cpython-3.12.5-macos-aarch64-none/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/Users/rohangodha/.local/share/uv/python/cpython-3.12.5-macos-aarch64-none/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/.local/share/uv/python/cpython-3.12.5-macos-aarch64-none/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/.local/share/uv/python/cpython-3.12.5-macos-aarch64-none/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/Users/rohangodha/.local/share/uv/python/cpython-3.12.5-macos-aarch64-none/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/.local/share/uv/python/cpython-3.12.5-macos-aarch64-none/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rohangodha/Coding/sonos/script.py", line 14, in <module>
    print(speaker.player_name)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/soco/core.py", line 392, in player_name
    self.zone_group_state.poll(self)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/soco/core.py", line 1613, in zone_group_state
    zgs = self.zone_group_states.get(self.household_id)
                                     ^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/soco/core.py", line 442, in household_id
    self._household_id = self.deviceProperties.GetHouseholdID()[
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/soco/services.py", line 207, in _dispatcher
    return self.send_command(action, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/soco/services.py", line 474, in send_command
    args = self.compose_args(action, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/soco/services.py", line 334, in compose_args
    for action in self.actions:
                  ^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/soco/services.py", line 682, in actions
    self._actions = list(self.iter_actions())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/soco/services.py", line 708, in iter_actions
    scpd_body = requests.get(self.base_url + self.scpd_url, timeout=10).content
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohangodha/Library/Caches/uv/archive-v0/OqGyAg4weCpbpk7kS6Mt7/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
</p>
</details> 

python 3.12.5, OpenSSL 3.0.14 4 Jun 2024, and I've tried installing "requests[security]" already. 
I've also tried python 3.8-3.12 and none have worked. I'm on macos 14.3
any ideas on what the issue could be?

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by pwt** [comment]
Hi:

SoCo calls are generally HTTP, not HTTPS. Could you confirm HTTP connectivity to the speaker, e.g.:

```
curl http://192.168.0.33:1400/xml/device_description.xml
```

Replace the IP address with that of your speaker.

**Comment by rgodha24** [comment]
I can't connect to port 80 (with curl) -- I'm just going to put this issue up to my university network having weird firewall settings. Thanks for your help!
